### ISSUE TITLE
How to remove new chunks from chunk finder?

### ISSUE THREAD

**Issue by boatfullogoats** [zeroeightysix/KAMI#116]
It seems when I use chunkfinder and load new chunks, the new chunks stay indefinitely if i disable the module or not. How would I go about removing these saved new chunks?

**Comment by S-B99** [comment]
Delete them from .Minecraft, I'm assuming they're cached there.

**Comment by zeroeightysix** [comment]
They are not cached in your `.minecraft` folder, instead they are kept in memory for the entirety of your session. I'll fix this soon.
