### ISSUE TITLE
Game Crash Forge Windows 10 1.12.2

### ISSUE THREAD

**Issue by BUNYIP24** [zeroeightysix/KAMI#122]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI (kami) 

was using kami with other mods every thing was working fine then i wake up the next day and my game will not start i removed every thing from my mods folder but kami and my game was still crashing i also tryed making a new installation in minecraft launcher but that did not work

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoaderForge (kami-b9-release (1).jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 10/5/19 11:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI (kami)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0  im not sure how to fix this

**Comment by S-B99** [comment]
Delete your .minecraft, back your settings and worlds up first if you want to keep those. And send the full log if it keeps happening

**Comment by zeroeightysix** [comment]
> Delete your .minecraft, back your settings and worlds up first if you want to keep those. And send the full log if it keeps happening

Unnecessary.
Make sure you're using the newest version of KAMI (might have to build this yourself).
This bug was fixed recently.

**Comment by S-B99** [comment]
Sorry, forgot it was yea. Thank you!
