### ISSUE TITLE
Bug: multiple sprint modules

### ISSUE THREAD

**Issue by awfol** [zeroeightysix/KAMI#125]
Multiple sprint modules in the Movement module list ingame.
note: could have to do with settings which are floats

[Screenshot](https://imgur.com/a/YS49vSc)

**Comment by blockparole** [comment]
I also experienced this some time ago, other people did too, just found this screenshot in discord history: [ss](https://cdn.discordapp.com/attachments/496724197121196033/612091877440618516/unknown.png)

**Comment by cookiedragon234** [comment]
https://github.com/S-B99/KAMI/issues/22#issuecomment-546729234 If @zeroeightysix wants to create an upstream fix

**Comment by S-B99** [comment]
https://github.com/S-B99/kamiblue/issues/22#issuecomment-546729234 (fixed repo link)

I'm not sure if it's using a new module manager by now but it's probably fixed in 1.14 branch

**Comment by dominikaaaa** [comment]
This is fixed in KAMI Fabric lol

**Comment by zeroeightysix** [comment]
I do have a hard time imagining this still happening - closing.
