### ISSUE TITLE
添加.tp指令和相应功能

### ISSUE THREAD

**Issue by minecraft-pig** [zeroeightysix/KAMI#128]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by S-B99** [comment]
Do you mean click tp?

你的意思是“Click TP”？

**Comment by minecraft-pig** [comment]
不是是.tp

**Comment by minecraft-pig** [comment]
tp距离更远的那种

**Comment by S-B99** [comment]
这是生存命令吗？

**Comment by minecraft-pig** [comment]
是的

**Comment by minecraft-pig** [comment]
请问kami还会更新吗

**Comment by S-B99** [comment]
i see what you mean. I'll look into adding it at my project. https://github.com/S-B99/KAMI

我明白你的意思了。 我会考虑将其添加到我的项目中。 https://github.com/S-B99/KAMI

**Comment by minecraft-pig** [comment]
谢谢

**Comment by minecraft-pig** [comment]
我有一份wurst的tp部分代码需要看一下吗

**Comment by S-B99** [comment]
Sure, I would appreciate that!

当然，我将不胜感激！

**Comment by minecraft-pig** [comment]
我改如何给你

**Comment by S-B99** [comment]
This would work https://gist.github.com/

这可以工作https://gist.github.com/

**Comment by minecraft-pig** [comment]
这个网站我打不开可能是因为中国的防火墙吧qwq

**Comment by S-B99** [comment]
Can you try these?

你可以试试这些吗？

Https://pastebin.com

Https://hastebin.com

**Comment by minecraft-pig** [comment]
可以上的谢谢

**Comment by Punydog** [comment]
Hi,there
I know what do you mean.
Sorry for my Bad english!
i am React Client developer and im going to add tp future to react
you can msg me for more infomation!

**Comment by S-B99** [comment]
Is react open source?

**Comment by minecraft-pig** [comment]
可能会吧qwq

**Comment by Punydog** [comment]
> Is react client open source?

Im glad you looks interesting,but React is a close-source client.
but i can show you another way to get teleport source.
because wurst is a opensource project.
just view wurstclient.net and found their github.

**Comment by minecraft-pig** [comment]
https://pastebin.com/Ex6Y5BH3
https://pastebin.com/GGCwuSDd
我没有用过这个网站看一下是不是可以看

**Comment by minecraft-pig** [comment]
wurstclient.com上的github的是1.14.4的源码我没有找到tp部分

**Comment by S-B99** [comment]
谢谢@minecraft-pig

**Comment by minecraft-pig** [comment]
是我要谢谢你开发了kami并且开源了

**Comment by ReactDevelop** [comment]
> 谢谢@minecraft-pig

你可以在net/wurstclient/futures里找到tp

**Comment by S-B99** [comment]
没问题。 086已经完成了大部分工作，由于086并不打算继续对其进行工作，因此我将继续对其进行工作。

**Comment by ReactDevelop** [comment]
> 没问题。 086已经完成了大部分工作，由于086并不打算继续对其进行工作，因此我将继续对其进行工作。

so please tell me your country for better communicate

**Comment by minecraft-pig** [comment]
谢谢如果可以请尽快更新新版本的kami我们都很期待

**Comment by minecraft-pig** [comment]
> > 没问题。086已经完成了大部分工作，由于086并不打算继续进行进行工作，因此我将继续进行进行工作。
> 
> 所以请告诉我您的国家以便更好地沟通

我翻译器用的很开心awa

**Comment by S-B99** [comment]
KAMI将在这里更新：https://github.com/S-B99/KAMI/releases

**Comment by S-B99** [comment]
uwu

**Comment by minecraft-pig** [comment]
我们期待你的更新awa

**Comment by ReactDevelop** [comment]
你如果不介意，可以为react提供某些技术帮助，我们或许会为你提供tp和auto32k源码

**Comment by S-B99** [comment]
谢谢，我不介意帮忙

**Comment by blockparole** [comment]
@minecraft-pig are you the guy selling free client releases [here](http://minecraftpig.maikama.cn/)?

**Comment by minecraft-pig** [comment]
> @ minecraft-pig您是[在这里](http://minecraftpig.maikama.cn/)销售免费客户端版本的家伙吗？

是的但是我是以服务为主但我并没有卖kami

**Comment by minecraft-pig** [comment]
> @minecraft-pig are you the guy selling free client releases [here](http://minecraftpig.maikama.cn/)?

可以告诉我你在那获取的网址或者在china2b2t的名字吗

**Comment by blockparole** [comment]
Oh i see, so its not cracked Future you are selling but rather the service to create an account?

**Comment by minecraft-pig** [comment]
yes

**Comment by S-B99** [comment]
https://futureclient.net/forum/ :clown_face:

**Comment by minecraft-pig** [comment]
如果他是免费并开源那多好

**Comment by d1gress** [comment]
it be done on kami blue

在 https://github.com/S-B99/KAMI 有了你要的特征。

**Comment by minecraft-pig** [comment]
谢谢

**Comment by zeroeightysix** [comment]
Closing: please consider submitting your issue(s) in English.
