### ISSUE TITLE
Distance-show tracer

### ISSUE THREAD

**Issue by snowmiii** [zeroeightysix/KAMI#129]
Tracer color should change when the distance change,like 4m long with green 10m long with orange.
And this can be add as a option in tracer 
would help a lot

**Comment by S-B99** [comment]
Isn't this already in another issue?

**Comment by snowmiii** [comment]
uhh ok
So is this module added

**Comment by S-B99** [comment]
Nevermind it's not in another issue

**Comment by S-B99** [comment]
Also this isn't being updated, only bugs are being fixed

**Comment by snowmiii** [comment]
ok lol

**Comment by zeroeightysix** [comment]
Not planning on adding this, as tracer colours are customisable and this would add a layer of complexity the average user would not enjoy.
