### ISSUE TITLE
CrystalAura attacks teammates

### ISSUE THREAD

**Issue by minecraft-pig** [zeroeightysix/KAMI#130]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zeroeightysix** [comment]
Try to fill out the template next time.
Have you tried adding your teammates to your friends list?
You may do so by using the `.friend`  command: `.friend add <username>`

下次尝试填写模板。
您是否尝试过将队友添加到朋友列表中？
您可以通过使用`.friend`命令来做到这一点：`.friend add <用户名>`

**Comment by zeroeightysix** [comment]
Going to assume invalid because no further information was provided in a months time.
