### ISSUE TITLE
Setting<Double> value range decimal places

### ISSUE THREAD

**Issue by blockparole** [zeroeightysix/KAMI#145]
When trying to implement a Setting in a Module like this:
`private Setting<Double> slipperiness = register(Settings.doubleBuilder("Slipperiness").withMinimum(0.2).withValue(0.4).withMaximum(1.0).build());`

**Actual behavior**
It results in a value with a lot of decimal places:
![](https://i.imgur.com/alMulsD.png)

**Expected behavior**
Something that is more user friendly, like the displayed value of floatBuilder:
![](https://i.imgur.com/9jl0KFV.png)

**Comment by S-B99** [comment]
Why can't you convert it to a float?

**Comment by S-B99** [comment]
Also if 086 sees this, supporting straight `int`s would be great. If I can find the example one of the modules I wanted to have an int setting for and settings only supports `Integer`

**Comment by blockparole** [comment]
Yeah well, if i wanna use a value thats not a whole numbers, then i have to use somethine else then Integer.

**Comment by blockparole** [comment]
> 
> 
> Why can't you convert it to a float?

Im doing that atm [here](https://github.com/zeroeightysix/KAMI/pull/146/files), but imho thats not a nice solution to this problem.

**Comment by blockparole** [comment]
> 
> 
> Also if 086 sees this, supporting straight `int`s would be great. If I can find the example one of the modules I wanted to have an int setting for and settings only supports `Integer`

Yeah well, if i wanna use a value thats not a whole number, then i have to use somethine else then Integer.

**Comment by S-B99** [comment]
This was loosely related sorry. Should honestly be in its own issue.
I meant the current setting system only supports `Integer` and not `int`

**Comment by zeroeightysix** [comment]
> This was loosely related sorry. Should honestly be in its own issue.
> I meant the current setting system only supports `Integer` and not `int`

Because the current system uses generics, and generics can't be primitive types. If you need the `int` value, just use `setting.getValue().intValue()` ([doc](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#intValue()))
