### ISSUE TITLE
 my chat is ruined now... [how to reproduce]

### ISSUE THREAD

**Issue by RajehTXD** [zeroeightysix/KAMI#148]
**Describe the bug**
ruins the entire chat system
**To Reproduce**
1.  Do '.prefix  '
2. now you cant chat
3. good game

**Expected behavior**
I was .prefix ? but then ii had an extra space

**Screenshots**
[Look here](https://ibb.co/sq1v0YB)

**Additional context**
I get error

**Comment by RajehTXD** [comment]
@zeroeightysix

**Comment by S-B99** [comment]
Did you run just .prefix by itself? 
I can't reproduce this

**Comment by RajehTXD** [comment]
it will keep on saying that shizzle in the screenshots. I knew how to fix this, the config contains a string that is label-ed commandprefix

it is not an efficient way of doing shizzle... suggestion: add a check to see if prefix is empty then return it to . with a message

**Comment by RajehTXD** [comment]
closed

**Comment by RajehTXD** [comment]
if you try anything that shizzle pops up

**Comment by S-B99** [comment]
Ig I'll try implementing this myself and make a pull if it works

**Comment by RajehTXD** [comment]
just set commandprefix to nothing
that happens

**Comment by RajehTXD** [comment]
shittt it didn't work

**Comment by RajehTXD** [comment]
I reinstalled kami and still no shot... btw how do I add custom chat characters... im going to delete my config files and see...

**Comment by RajehTXD** [comment]
Im going to leave this open for further replies. if you ever experience this. be sure to let me know.. the 
![2019-11-22_20 03 26](https://user-images.githubusercontent.com/52720753/69455189-88275a00-0d70-11ea-9254-e4da7f747344.png)
screenshot indepth… if you are scared to click

**Comment by S-B99** [comment]
You run the command with your prefix

**Comment by RajehTXD** [comment]
it is fixed... delete config

**Comment by RajehTXD** [comment]
also how to change customchat

**Comment by RajehTXD** [comment]
as default it says KAMI in small letters

**Comment by S-B99** [comment]
To change customchat you have to edit CustomChat.java and recompile.

**Comment by RajehTXD** [comment]
where do I find that?

**Comment by RajehTXD** [comment]
nvm thanks I got it

**Comment by RajehTXD** [comment]
I got it now... how did I mess up... 
when I did .prefix  ? I added extra space, but I had the question mark, so kami didn't detect that it is a space, and ignored ?

**Comment by RajehTXD** [comment]
closed for resolved
