### ISSUE TITLE
[QUESTION] {Not a issue} Could we add modules?

### ISSUE THREAD

**Issue by RajehTXD** [zeroeightysix/KAMI#149]

**Comment by S-B99** [comment]
Yes. Also question label exists.

**Comment by RajehTXD** [comment]
how to add labels

**Comment by S-B99** [comment]
![Screenshot_20191122_155026](https://user-images.githubusercontent.com/17222512/69459468-cfe1bd80-0d3f-11ea-9671-8022bf63ea2a.png)

**Comment by RajehTXD** [comment]
cant click that

**Comment by S-B99** [comment]
It's a screenshot

**Comment by RajehTXD** [comment]
the labels
thigy

**Comment by S-B99** [comment]
uhh then I think only project collaborators have permissions to do labels? oof

**Comment by zeroeightysix** [comment]
> Yes, you can add modules. Make a fork and then a pull request. Also question label exists.

This. For suggestions, feel free to open a issue to suggest a feature. If you know how to implement it, make a fork, implement it and create a pull request and I'll review it.
