### ISSUE TITLE
FloatSlider is fixed, Settings without the slider not tho

### ISSUE THREAD

**Issue by 3arthqu4ke** [zeroeightysix/KAMI#150]
![Slider](https://user-images.githubusercontent.com/56741599/69499976-90f66800-0ef7-11ea-8d8a-a3af5cf9abef.png)

New fix is nice works for settings like this:
private Setting<Float> red = register(Settings.floatBuilder("Red").withMinimum(0f).withMaximum(1.0f).withValue(1.0f).withVisibility(o -> renderrgba.getValue()).build());

but not for stuff like this:
private Setting<Float> float = register(Settings.f("Float", 1.0f));

**Comment by 3arthqu4ke** [comment]
whoops not true, but doesnt matter for the point

**Comment by zeroeightysix** [comment]
Oops, my bad - I only applied the fix to bound sliders!
