### ISSUE TITLE
Distance Option for 32K

### ISSUE THREAD

**Issue by DontEatOreo** [zeroeightysix/KAMI#154]
**Is your feature request related to a problem? Please describe.**
This is an add-on for already existing 32k module it just draws a square box of the place where the hopper is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
The purpose is that u can see if you're about to go out of distance.

Another thing is after set ticks or time the hopper gui could be hidden so you can see better.

**Comment by dominikaaaa** [comment]
I don't think this is very useful now that 32ks are patched on all mainstream servers
