### ISSUE TITLE
[Bug] Antifog does not work above y 126

### ISSUE THREAD

**Issue by edwr** [zeroeightysix/KAMI#170]
**Describe the bug**
Fog appears at y 126 and above in overworld with AntiFog enabled.

**To Reproduce**
1. Enable AntiFog
2. Go above y 126
3. Observe bug

**Expected behavior**
The expected behavior is for there to be no fog.

**Screenshots**

**Additional context**
AntiFog also has some other weird bugs and visual glitches that I'm having trouble reproducing.

**Comment by zeroeightysix** [comment]
What mode is AntiFog on? Does it happen for both modes?

**Comment by edwr** [comment]
AntiFog is on mode NOFOG. AIR mode doesn't even get rid of fog at normal y level lol.

**Comment by zeroeightysix** [comment]
> AntiFog is on mode NOFOG. AIR mode doesn't even get rid of fog at normal y level lol.

What other mods are you running?

**Comment by edwr** [comment]
Tested with and without optifine and the same thing happens.

**Comment by edwr** [comment]
I think the bug is related to minecraft's cloud rendering since clouds render at y 127

**Comment by zeroeightysix** [comment]
See #172
