### ISSUE TITLE
[Bug] Turning off clouds breaks Antifog

### ISSUE THREAD

**Issue by edwr** [zeroeightysix/KAMI#171]
**Describe the bug**
Turning off clouds in video settings causes Antifog to not get rid of fog.

**To Reproduce**
1. Go to minecraft video settings and set clouds to off
2. Enable Antifog
3. Observe bug

**Expected behavior**
Fog disappears.

**Screenshots**

**Additional context**
Tested with and without optifine and with both modes of AntiFog.

**Comment by S-B99** [comment]
Also if there is no fog, it creates fog.

**Comment by zeroeightysix** [comment]
See #172
