### ISSUE TITLE
[Bug] Closing and reopening minecraft causes AntiFog visual glitch

### ISSUE THREAD

**Issue by edwr** [zeroeightysix/KAMI#172]
**Describe the bug**
Closing and reopening minecraft while AntiFog is enabled (NOFOG mode) and going above y 126 causes visual glitch which makes it hard to see anything.

**To Reproduce**
1. Enable AntiFog in NOFOG mode
2. Close minecraft
3. Reopen minecraft
4. Go above y 126
5. Observe bug

**Expected behavior**
Visual glitch does not occur and AntiFog behaves as normal.

**Screenshots**

**Additional context**
This bug does not occur in AIR mode. Tested with and without optifine.

**Comment by 20kdc** [comment]
er, do excuse my accidental notification, was trying to make a KAMI Blue PR but GitHub forks are picky about re-forking an existing fork
to avoid me having to write *a lot* of comments like these, consider this comment the reference.

**Comment by S-B99** [comment]
Huh lmao. It shows me as an author in the picture, but it is your commit to your repo. I'm not quite sure how it's possible or what is happening here lol.

**Comment by 20kdc** [comment]
It says I pushed "a commit", but looking at the commit details authorship info inside the commit is properly preserved. But GitHub's not properly stating the authorship on the notification message. Hm.

**Comment by S-B99** [comment]
Honestly to me it looks like a github bug or your github desktop somehow fucked it up badly.

**Comment by 20kdc** [comment]
I'm not using GitHub desktop.
What I don't get is why it notified for someone else's commits, at all.
All the metadata was properly attached.

**Comment by S-B99** [comment]
Mhm, me neither. Sorta off topic anyways.

**Comment by zeroeightysix** [comment]
AntiFog was rewritten in KAMI fabric and this probably won't occur anymore - feel free to reopen if it does (on fabric!!)
