### ISSUE TITLE
Command system is case-sensitive

### ISSUE THREAD

**Issue by dominikaaaa** [zeroeightysix/KAMI#195]
Running `.t sprint` gives an error, while the autocomplete shows Sprint, commands should ignore case for stuff such as module names and binds.

**Comment by zeroeightysix** [comment]
Thanks!

**Comment by dominikaaaa** [comment]
Fixed in https://github.com/zeroeightysix/KAMI/commit/173e18881d6e2d4573449aea32a6a5570b53066a

**Comment by dominikaaaa** [comment]
:P you were a bit faster

**Comment by zeroeightysix** [comment]
The commit actually has the 'Closes' keyword, so I don't get why the push didn't close it.
