### ISSUE TITLE
Crash when trying to list settings for certain modules when installed alongside the Fabric API

### ISSUE THREAD

**Issue by JerryWester** [zeroeightysix/KAMI#203]
**Describe the bug**
The game crashes upon attempting to list settings of specific modules (i.e. EntitySpeed) on a built jar.

**To Reproduce**
1. Build the jar file and put it in a Minecraft installation alongside the Fabric API.
2. Attempt to use `.settings list EntitySpeed` or `.settings set EntitySpeed`
3. Crash

**Expected behavior**
Some modules work fine (i.e. Aura) but others cause a crash. All modules' settings should behave the same.

**Comment by zeroeightysix** [comment]
Works for me in a development environment, can you post the error?

**Comment by JerryWester** [comment]
Currently away from my computer, I'll post a log when I get back to it

**Comment by JerryWester** [comment]
UPDATE: KAMI works fine by itself, but has issues with another mod. I'll work on pinpointing which one it is, but until then, [here's a crash log](https://gist.github.com/JerryWester/d355fa3c5da4823e57be658ef9896d71)

**Comment by JerryWester** [comment]
KAMI has conflicts with the Fabric API. [New Crash Log](https://gist.github.com/JerryWester/cec4607d68fd7adc01dbdf2f91e87ba4). Will update both mods to see if the issue persists.

**Comment by zeroeightysix** [comment]
KAMI uses some minecraft code for its registries. I'm not sure why that's interfering with fabric API, but since 1.16.1 minecraft's registries are kind of annoying to use anyways - KAMI doesn't need the features it provides. I'll switch to a simpler kind of registry for KAMI.

**Comment by zeroeightysix** [comment]
Can you try again with face07d417a53feda77705d1ef9946d45257d3d5?

**Comment by JerryWester** [comment]
Looks like that commit fixes it, thank you!
![2020-08-08_14 22 47](https://user-images.githubusercontent.com/15377985/89719195-04a3ac80-d983-11ea-84e3-8efbed2f1e31.png)
