### ISSUE TITLE
Changing enum values in-game causes a crash

### ISSUE THREAD

**Issue by JerryWester** [zeroeightysix/KAMI#205]
**Describe the bug**
Attempting to set an "enum" setting in-game causes a sudden crash.

**To Reproduce**
1. Attempt to set a value to any enumerated setting (i.e. `.settings set Flight Mode JUMP`)
2. Crash

**Expected behavior**
An error thrown in chat, or a list of possible settings.

**Additional context**
Crash log: https://gist.github.com/JerryWester/97e3dc249faee2421f48a64479ef827f

**Comment by dominikaaaa** [comment]
I fixed this in KAMI Blue a while back, lemme find the commits

**Comment by zeroeightysix** [comment]
@dominikaaaa No need - the settings rewrite means your fix won't work.

**Comment by dominikaaaa** [comment]
oh yea I'm so stupid. My brain did a :woman_facepalming:

**Comment by JerryWester** [comment]
UPDATE: It's not just an issue with invalid values. For example, trying to change the flight mode to `STATIC` (a valid value) also causes a crash.
