### ISSUE TITLE
ClickGUI can't be toggled & crashes when attempting to list settings

### ISSUE THREAD

**Issue by JerryWester** [zeroeightysix/KAMI#207]
**Describe the bug**
Attempting to use `.toggle ClickGUI` causes it to "toggle off", even when it isn't on. Trying to list the settings of ClickGUI causes a crash.

**To Reproduce**
1. Enter `.toggle ClickGUI` into chat.
2. Proceed to be told ClickGUI was toggled off.
3. Attempt to list settings of ClickGUI (`.settings list ClickGUI`).
4. Crash.

**Expected behavior**
A GUI to toggle modules should pop up / settings should be listed.

**Additional context**
[latest.log](https://gist.github.com/JerryWester/0fd9b15642ea08625c5948e1595297eb)

**Comment by JerryWester** [comment]
Workaround: you can still use `.settings set ClickGUI Bind`, and open the GUI through that bind

**Comment by zeroeightysix** [comment]
A little bit of an explanation as b7f1f4c might not seem related to this issue:

1. `ClickGui` is no longer a 'full feature' (such as a module or plugin) - it simply has a name and a bind. Thus, the `toggle` command does not apply to it anymore, as `ClickGui` has no 'enabled' state.
2. The settings command no longer shows invisible settings such as `Enabled`, `Name` or `Bind`. Use the `toggle` and `bind` commands.
