### ISSUE TITLE
A PortalLogger

### ISSUE THREAD

**Issue by michuthecomrade** [zeroeightysix/KAMI#21]
The folks at The Society Project would really appreciate a module known as PortalLogger. It  ideally would be toggleable and log all portals that come within the players render distance inside an easily exportable .txt file. 

A module like this could allow us to measure player density, which is one of our main goals.

**Comment by zeroeightysix** [comment]
This is another quite specific module, like #20. I'll consider work on this, but it'll probably be in the form of either another macro mod or in-game scripting embedded in KAMI. (far future)

**Comment by wine** [comment]
@michuthecomrade if you feel like this is something that really **has** to be added, re-open the issue

**Comment by zeroeightysix** [comment]
This is actually a good example of something that may be implemented using a plugin. See #45

**Comment by wine** [comment]
@zeroeightysix I'm willing to make the actual plugin for this, if we implement a plugin system
