### ISSUE TITLE
Modules bound to NONE get activated when pressing pause/play button

### ISSUE THREAD

**Issue by tyrannus00** [zeroeightysix/KAMI#212]
I am using a media key on my mouse that allows me to pause/play music without opening e.g. spotify, but everytime I press this button every module that is bound to none, gets toggled. I cant use kami because of this since my music is more important to me :/

**Comment by dominikaaaa** [comment]
Is this on the fabric or forge version?

**Comment by tyrannus00** [comment]
Sorry, this happens on the latest 1.16.2 fabric release.

**Comment by zeroeightysix** [comment]
Confirmed

**Comment by dominikaaaa** [comment]
This happens because volume keys count as GLFW.KEY_NONE on most systems
 You fixed it in KAMI by adding a simple return in the bind system

https://github.com/kami-blue/client/blob/ef0bff9813c66c9397f48a2e1ae79dd8dfa4e760/src/main/java/me/zeroeightsix/kami/module/ModuleManager.java#L93
