### ISSUE TITLE
Markers equivalent?

### ISSUE THREAD

**Issue by michuthecomrade** [zeroeightysix/KAMI#22]
The PortalTracers are currently an issue, but why not replace them with a Markers equivalent? It would allow for more customizability.

**Comment by ZeroMemes** [comment]
If this issue is referring to the functionality of the markers module in ForgeHax, make sure to use VBOs when rendering the bounding boxes.

**Comment by S-B99** [comment]
PortalTracers was removed so this should be closed and or updated.

**Comment by zeroeightysix** [comment]
> PortalTracers was removed so this should be closed and or updated.

Feel free to create a new issue or reopen this one.
