### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by groovyspacetruck** [zeroeightysix/KAMI#224]
I instaled the file as instructed, and also instaled Fabric. I put the KAMI AUG RELEASE file onto the Mods folder, already having instaled Fabric. I tried to join a multiplayer game, it loads, it says login in and crashes with this message EXCEPTION_ACCESS_VIOLATION (0xc0000005)

**To Reproduce**
1 download KAMI AUG RELEASE, instal Fabric, Drag Kami into Mods, Load 1.16.2 version, go to multiplayer, join desired server.

**Expected behavior**
I expected to be able to play with Kami.

**Environment**
Java is in the lattest version (July 14th)
https://paste.ubuntu.com/p/qRbq7nxHQK/

**Comment by dominikaaaa** [comment]
Pretty sure this is already fixed

**Comment by JerryWester** [comment]
🤔 Then how is it happening here?

**Comment by dominikaaaa** [comment]
Because they're not running the latest version

**Comment by zeroeightysix** [comment]
This is not fixed.

**Comment by JerryWester** [comment]
Oh, you're referring to commits, not release

**Comment by dominikaaaa** [comment]
Also you fucked up your markdown, here's the proper link for anybody who wants to be able to click it on mobile: https://paste.ubuntu.com/p/qRbq7nxHQK/

**Comment by zeroeightysix** [comment]
Does this happen every time you try to join a world?

**Comment by groovyspacetruck** [comment]
I'm running the latest version, in single player seems to work just fine, multiplayer is the problem

**Comment by zeroeightysix** [comment]
> I'm running the latest version, in single player seems to work just fine, multiplayer is the problem

That's very strange. Does the HUD render correctly in singleplayer? Have you tried joining other servers?
If it works on other servers, do you mind sharing which server you are trying to join that crashes KAMI?

**Comment by groovyspacetruck** [comment]
I fixed it, the roblem was on my end, I think Java.exe and Javaw. didn't have certain permitions. thank you very much for the help! sorry for bothering

**Comment by zeroeightysix** [comment]
> I fixed it, the roblem was on my end, I think Java.exe and Javaw. didn't have certain permitions. thank you very much for the help! sorry for bothering

Please share what exactly you did to fix it. I've had another user have a near identical JVM crash, so I bet this may be useful in the future.

**Comment by groovyspacetruck** [comment]
so, you go to your minecraft launcher folder, go to Runtime, then you to go jre-x64 - > Bin. then look for Java.exe, right click, left click on propreties, then go to compatibility and enable Run as Admin. then do the same for Javaw.exe. Open minecraft and the create a single player world, then join multiplayer.
