### ISSUE TITLE
Optifabric compatibility

### ISSUE THREAD

**Issue by Sigha0160** [zeroeightysix/KAMI#225]
Does not launch with optifabric

**Comment by zeroeightysix** [comment]
Please post a crash log.

Also, I highly recommend https://github.com/jellysquid3/sodium-fabric (and other mods by the same author, with mineral names) instead of optifine.

**Comment by humboldt123** [comment]
Why did you close this one? @zeroeightysix

**Comment by 5HT2** [comment]
![Screenshot_20200925-075253.png](https://user-images.githubusercontent.com/17222512/94264121-21307f80-ff04-11ea-8c18-3f49729387e1.png)

**Comment by humboldt123** [comment]
Oops- I misread and thought he closed that one.

**Comment by Rajbir98** [comment]
### Optifabric is incompatible with huge amount of mods plz fix it ###

**Comment by JerryWester** [comment]
There is a reason OptiFabric is incompatible with a huge amount of mods.
