### ISSUE TITLE
Gui Positioning

### ISSUE THREAD

**Issue by sourTaste000** [zeroeightysix/KAMI#227]
# Describe the bug
The fixed positioning preview doesn't match the real position.
**If you are confused, go to the screenshots section.**

# To Reproduce
1. Press `Y`
2. Right-click on any overlay(Information, Module list)
3. Choose any fixed position
4. Press `Y` again
5. Preview in kami GUI doesn't match the real position when exiting the GUI.

# Expected behavior
It should keep in the same position.

# Screenshots
![preview](https://user-images.githubusercontent.com/47074495/92653804-b9432d80-f2a3-11ea-9811-a7fea43fc9ab.gif)

**Environment**
Built kami on commit 7fe6e56da7f304fc52a21453dd75d3d11715deab
Operating system: macOS Catalina 10.15.6
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

**Additional context**
Nice coords kekw

**Comment by humboldt123** [comment]
Yeah you have to do it manually

**Comment by sourTaste000** [comment]
You have to move it off the screen if you want it to be in the correct position.

**Comment by zeroeightysix** [comment]
I can't reproduce this due to having a screen too small, so I can't make for sure it's fixed either. Please don't hesitate to reopen if 09d437b didn't fix it.

**Comment by kibibites** [comment]
Minecraft font breaks the positioning, please reopen

**Comment by kibibites** [comment]
Video: http://ge.tt/8owBEJ83
sorry for poor quality

**Comment by kibibites** [comment]
Stale
