### ISSUE TITLE
Add in more GUI customizability.

### ISSUE THREAD

**Issue by michuthecomrade** [zeroeightysix/KAMI#23]
Kami is one of the mods that are nicer graphically and that can allow the user to adjust the GUI to their needs. However, often the text goes out of the 'rectangle' that the user put the module of the GUI in. For instance, while traveling greater distances, the coords can go out of the window, which often can be a bother!

**Comment by zeroeightysix** [comment]
This is planned for when I finish GUI revamp! (See progress over at https://github.com/zeroeightysix/jtcui)

**Comment by zeroeightysix** [comment]
See #51
