### ISSUE TITLE
New options for ESP module

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#237]
**Is your feature request related to a problem? Please describe.**
A lot of storage containers are missing from the ESP module, currently only Chests, Trapped Chests and Shulker Boxes have proper categories.
I don't really know if adding a lot of storage stuff to the ESP module is a good idea, since the descrition of the module is "Draws outlines around targetted entities" but that is your decision.

**Describe the solution you'd like**
Missing storage containers that should (probably/hopefully) be added:
- Minecart with Hopper;
- Minecart with Chest;
- Ender Chest;
- Item Frame;
- Furnace;
- Dropper;
- Dispenser;
- Hopper;
- Blast Furnace;
- Smoker;
- Barrel;
- Lectern.

**Describe alternatives you've considered**
I don't think there is any in this specific utility mod.

**Additional context**
No.

**Comment by humboldt123** [comment]
@zeroeightysix assign me I can do this.

**Comment by zeroeightysix** [comment]
This should be really easy. Just add more entries to the `BlockTarget` enum.
