### ISSUE TITLE
EntitySpeed still applied when using Freecam

### ISSUE THREAD

**Issue by zfih** [zeroeightysix/KAMI#249]
**Describe the bug**
Whenever freecam is on and the player is in a vehicle, the movement input is still applied to the vehicle, moving both the vehicle and the player in the same way as the camera.
This only affects movement input but not camera input

**To Reproduce**
1. Mount vehicle (tested with boats and horses)
2. Turn on Freecam
3. Move backwards and the character will follow backwards.

**Expected behavior**
Player and vehicle stays stationary like when not mounted.

**Environment**
Latest commit (https://github.com/zeroeightysix/KAMI/commit/9a47d6b282f4c0cc22bfe3fce22c0d4c5f836314) on fabric branch, self compile, no changes.

**Comment by zeroeightysix** [comment]
Cannot reproduce. Tried both minecart and horse. What vehicle(s) are you using? Can you maybe post a video of the behaviour?

**Comment by zfih** [comment]
I did some more testing, this only happens when entity speed is on.
Here is a short vid of it
https://gfycat.com/threadbareklutzyicelandichorse-minecraft-freecam-client-bug

**Comment by zeroeightysix** [comment]
Looks like this is an EntitySpeed bug then. EntitySpeed's `steerBoat` uses not the player input, but the key states - should probably remove that function and have it use the same code as other rideables.

**Comment by zfih** [comment]
Ok, I might have time to look at it tomorrow myself. If I do I'll look at that function

**Comment by zeroeightysix** [comment]
Awesome! I'll assign you, but if it turns out you don't have the time or you can't find a solution, feel free to tell me to unassign you.

**Comment by zfih** [comment]
Gotcha, I will

**Comment by zfih** [comment]
Had to do a dumb force push but here is the pull request. I have tested with boats and horses and it seems to work as intended now
