### ISSUE TITLE
Discord RPC incompability with macOS

### ISSUE THREAD

**Issue by kibibites** [zeroeightysix/KAMI#250]
**Describe the bug**
Discord RPC doesn't show up properly on macos.

**To Reproduce**
1. Buy an Apple computer.
2. Download KAMI
3. Launch it and turn on Discord RPC
4. Observe error.

**Expected behavior**
The Discord RPC should show up properly.

**Screenshots**
N/A

**Environment**
<img width="658" alt="Screen Shot 2020-09-25 at 9 03 59 AM" src="https://user-images.githubusercontent.com/47074495/94289758-0ebb4380-ff0e-11ea-8bad-7022e343e786.png">
Platform: x86_64
Java version: 1.8.0_261

**Additional context**
N/A

**Comment by humboldt123** [comment]
Can't repro, stuck on step 1.

**Comment by Tigermouthbear** [comment]
Easy fix, replace step 1 with "Buy a Windows computer"

**Comment by JerryWester** [comment]
Also can't reproduce, please send in your Apple computer for testing.

**Comment by kibibites** [comment]
See https://github.com/Vatuu/discord-rpc/issues/12

**Comment by Tigermouthbear** [comment]
Id recommend switching to https://github.com/MinnDevelopment/java-discord-rpc instead of using vatuu's

**Comment by humboldt123** [comment]
It's a dead project. Its archived and the last update was three years ago.

**Comment by 5HT2** [comment]
So little of KAMI Blue's users use OSX, I'd wager KAMI is the same. It's pretty minor of a thing to switch to a deprecated library to fix

**Comment by zeroeightysix** [comment]
Unfortunately, this is not something I'm particularly interested in fixing - I don't have that much time to begin with and this is quite minor, with a small percentage of affected users.

If you really want this to work, I'd suggest opening a PR with a fix to vatuu's discord-rpc, or supporting the project in another way to get the bug fixed.
