### ISSUE TITLE
Option for neutral mobs under ESP

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#252]
**Is your feature request related to a problem? Please describe.**
Not really a problem, depends how you look at it.

**Describe the solution you'd like**
Add an option for neutral mobs under ESP, detect when (if) they become hostile and make their ESP use the hostile color.
Currently there are only options for hostile and passive, and neutrals are detected as hostile (tested with enderman and pigman) which is just incorrect.

**Describe alternatives you've considered**
Continue using the module as is.

**Additional context**
No.

**Comment by 5HT2** [comment]
<https://github.com/kami-blue/client/blob/master/src/main/java/me/zeroeightsix/kami/util/EntityUtils.kt>

This was ported from the original KAMI and had some bugs fixed (ie the original neutral mobs check didn't work properly on some states of endermen / pigmen)

Just yoink it

**Comment by zeroeightysix** [comment]
Fixed with target system
