### ISSUE TITLE
PortalChat option for inventory

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#253]
**Is your feature request related to a problem? Please describe.**
Not a problem, just convenience.

**Describe the solution you'd like**
A PortalChat option to open the player inventory. Currently only chat works trough portals, which makes sense since the name of the module is "PortalChat", but a lot of other utility mods also lets you open the inventory.

**Describe alternatives you've considered**
There is none.

**Additional context**
No.

**Comment by 5HT2** [comment]
It used to work with inventories, this is probably an issue from fabric porting

**Comment by zeroeightysix** [comment]
If it doesn't work with inventories, then this is actually a bug..
