### ISSUE TITLE
Option for neutral mobs under Aura

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#259]
**Is your feature request related to a problem? Please describe.**
Yes, attacking a zombie pigman by accident is a nightmare.

**Describe the solution you'd like**
Add an option on the Aura module for neutral mobs. The module should autodetect when (if) the neutral mob becomes hostile and use the hostile settings. Currently neutral mobs are treated as hostile, which is just incorrect.

**Describe alternatives you've considered**
Not using Aura.

**Additional context**
No.

**Comment by zeroeightysix** [comment]
(should be) fixed with targets
