### ISSUE TITLE
A module to search for blocks of interest

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#260]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a HUGE convenience.

**Describe the solution you'd like**
Add a module that searches blocks and block entities within render distance and highlights (ESP) blocks of interest, and an option for tracers to those blocks. Blocks of interest would include end portal frames, possibly end portals, nether portals and storage units, all of them should be user configurable. Color options also would be nice, if that can be done in a reasonable manner.
Modules like that are generally called "Search". I recommend using a similar name to prevent confusion.

Justification:
- This is useful to find stashes;
- This is useful to find end portals.

**Describe alternatives you've considered**
Using the normal ESP? But that only works on some storage units and cannot be considered an appropriate option in this case, also they don't have tracers.

**Additional context**
See KAMI Blue Search module.

**Comment by JerryWester** [comment]
Block ESP is being worked on by @zeroeightysix atm

**Comment by omninope** [comment]
@086 Are you sure about #274 closing this?
Please take this as just a **opinion** on why I think closing this was incorrect. At the end of the day the mod is yours and you do whatever you want with it.

Now my opinion:
The part about searching and highlighting stuff in render distance is in fact done, with the custom target support, that part is ok, but what about the tracers? Looking at every single angle trying to find the ESP isn't fun at all, and if the player is trying to find stashes, they can be located at almost height limit (I've seen a lot of them in the sky) now the player also has to look up to find the ESP since there is no tracers.
But adding blocks to the tracer is a good idea? No.

I suggested creating another separate module and call it "Search" for a reason ... well, 2 reasons:
- A lot of other utility mods have this type of module with this name doing what I described: Highlighting and showing tracers to whatever you add to the search list, this is literally a search;
- The module "ESP" is just for highlighting stuff, the module "Tracers" is for entities, the combination of ESP with an especialized Tracer makes a "Search" module, but even if Tracers supported blocks, using them separate will only cause problems: Imagine you want to search for stashes, you have to configure all the targets on the 2 modules, and when you finish you have to remove everyting excentric you added so you can use them as normal, this is not ideal to say the least. Yes, the player can make a config, but will still have to configure the blocks on 2 separate modules, and at the end it's just one more inconvenience that could be corrected with a module the player can just bind to a key, add whatever the hell the player wants to search and toggle on and off whenever the player feels like it.

If you can, take look at KAMI Blue's Search module.

**Comment by zeroeightysix** [comment]
This was mostly closed due to the function of 'block esp' being filled, and me forgetting that you ever mentioned tracers in this issue at all.

I agree with your input. Feel free to reopen & rename this issue, or create a new one for tracers specifically. (I will keep in mind to organise both features into one module)
