### ISSUE TITLE
Colormatic mod incompatibility

### ISSUE THREAD

**Issue by humboldt123** [zeroeightysix/KAMI#263]
**Describe the bug**
Minecraft is stuck in an infinite resource pack loading loop

**To Reproduce**
1. Apply a resource pack with no mods
2. Launch minecraft with the Colormatic mod and KAMI

**Expected behavior**
Minecraft works as normal with working resource packs

**Environment**
#247

**Comment by humboldt123** [comment]
Log
[latest.log](https://github.com/zeroeightysix/KAMI/files/5294385/latest.log)

**Comment by JerryWester** [comment]
Seems to me like it's just a Colormatic issue. Try booting without KAMI and see what happens

**Comment by zeroeightysix** [comment]
Closed as colormatic is not for 1.16.3

**Comment by JerryWester** [comment]
That would make sense then
