### ISSUE TITLE
Improvement suggestions for the Tracers module

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#264]
**Is your feature request related to a problem? Please describe.**
No, just cosmetic improvements.

**Describe the solution you'd like**
I would like to suggest the following cosmetic improvements to the Tracers module:
- Smoothing in the lines used, because currently they look like a staircase;
- Thickness option for the lines.

**Describe alternatives you've considered**
Continue using the tracers as is.

**Additional context**
No.

**Comment by zeroeightysix** [comment]
Unfortunately both line antialiasing and line thickness are not supported by all GPUs, but I'll look into this
