### ISSUE TITLE
Items option in Nametags module

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#265]
**Is your feature request related to a problem? Please describe.**
Not a problem, just convenience.

**Describe the solution you'd like**
An Target option in the Nametags module dedicated to items.
If this is going to be added, in the Options tab only the Colour option will be useful, probably remove the rest for this specific Target, if this is even possible to do on a single type of Target.

Justification:
- In a glance you can identify items of interest far away and not waste your time going there and discovering is was just dirt.

**Describe alternatives you've considered**
Im aware that if you set Targets to "Not living" it shows nametags to items, but also shows the nametags to all types of minecarts and item frames, which just causes confusion.

**Additional context**
No.

**Comment by zeroeightysix** [comment]
Implementing the exceptions would be far more effort than just adding the target, and frankly, against KAMI's design decisions.

Adding the category is no problem though.
