### ISSUE TITLE
improve name tags 

### ISSUE THREAD

**Issue by a-a3458** [zeroeightysix/KAMI#269]
**Is your feature request related to a problem? Please describe.** yes so when you have the name tags on it still shows the acutal ones as well.
 clear and concise description of what the problem is. Ex. I'm always frustrated when [...] it still shwoing both name tags 

**Describe the solution you'd like** add a option to hide the player tags to where it only shows the name tags 

**Describe alternatives you've considered** 

**Additional context**

**Comment by a-a3458** [comment]
bascially when you have name tags on it still shows the normal player tags

**Comment by a-a3458** [comment]
but like both show up

so you got the normal player tag and the name tag

**Comment by 5HT2** [comment]
this is fixed in latest

**Comment by zeroeightysix** [comment]
Already fixed.
