### ISSUE TITLE
Kami Crashing to desktop with Fabritone.

### ISSUE THREAD

**Issue by MaskForce** [zeroeightysix/KAMI#271]
**Describe the bug**
A Crash to desktop when loading a 1.16.2 Singleplayer world and a 1.16.x Multiplayer server.

**To Reproduce**
Have Fabric-Api-0.22.1+build.409-1.16, fabritone-1.16.2 and kami-1.16.2-aug and nothing else in .minecraft/mods folder.
Load up Fabric launcher 1.16.2
Start any Minecraft world/server
Crash to desktop.

**Expected behavior**
The mods to work fine in conjunction and load the world only. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38042795/94998696-b36dfe80-0568-11eb-942a-deea054002bd.png)
![image](https://user-images.githubusercontent.com/38042795/94998779-3b540880-0569-11eb-8907-fd56e3a3b0a1.png)

**Environment**
Kami August release 1.16.2
Windows 10 latest version.
Java 64 Bit Version 8 Update 261

**Additional context**
I have the crash logs here:
[crash-2020-10-02_22.22.41-client.txt](https://github.com/zeroeightysix/KAMI/files/5322101/crash-2020-10-02_22.22.41-client.txt)
[crash-2020-10-03_11.00.23-client.txt](https://github.com/zeroeightysix/KAMI/files/5322102/crash-2020-10-03_11.00.23-client.txt)
[crash-2020-10-03_11.04.18-client.txt](https://github.com/zeroeightysix/KAMI/files/5322103/crash-2020-10-03_11.04.18-client.txt)
[crash-2020-10-03_11.06.28-client.txt](https://github.com/zeroeightysix/KAMI/files/5322104/crash-2020-10-03_11.06.28-client.txt)
[crash-2020-10-02_22.20.27-client.txt](https://github.com/zeroeightysix/KAMI/files/5322105/crash-2020-10-02_22.20.27-client.txt)

**Comment by 5HT2** [comment]
Use the latest version of KAMI

**Comment by MaskForce** [comment]
This is the latest release. Unless there is a 1.16.3 release that I am missing?

**Comment by 5HT2** [comment]
You have to build it yourself 
![Screenshot_20201003-142219.png](https://user-images.githubusercontent.com/17222512/94998967-e2459e00-0583-11eb-83c1-e7e5d1f226f2.png)

**Comment by MaskForce** [comment]
If you say so. Not quite sure on how to build these things but I'll give it a try!
