### ISSUE TITLE
Caramelldansen option for Fullbright

### ISSUE THREAD

**Issue by JerryWester** [zeroeightysix/KAMI#273]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An option for Fullbright that adds a rainbow rave effect to the screen and plays an audio file named `caramelldansen` somewhere in the `.minecraft` folder (doesn't have to include said audio, just give the user the option to put it in themself)

**Describe alternatives you've considered**
N/A

**Additional context**
https://cdn.discordapp.com/attachments/541327608286019615/761787251033243679/9AuNdN6ttE.mp4

**Comment by zeroeightysix** [comment]
Feel free to write a plugin for this, but I don't think it's something I'll be working on (or would accept a PR for).

Sorry!
