### ISSUE TITLE
Aura breaks Nametags and Tracers for living entities

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#275]
**Describe the bug**
Nametags for "Passive", "Hostile" and "Living" targets only show during the hand charging animation that appears when the player select another slot with a different item, use an item or after using a tool.

**To Reproduce**
1. Build KAMI;
2. Enter into a normal world;
3. Enable the Nametags module and select "Passive", "Hostile" or "Living";
4. Look around, there are no nametags;
5. Get some items in the hotbar an scroll between them;
6. Briefly see the nametags.

**Expected behavior**
The nametags should show up when enabled.

**Screenshots**
No.

**Environment**
Did you build KAMI yourself? If so, on what commit? If not, which release did you download?
Build, commit: 5995bf76ecf7d6df52a7180749c4b17f93b1bae1

What operating operating system?
`uname -a` gives: `Linux debian 5.7.0-3-amd64 #1 SMP Debian 5.7.17-1 (2020-08-23) x86_64 GNU/Linux`.

What version of java?
`java -version` gives: `Java(TM) SE Runtime Environment (build 1.8.0_221-b11)`.

**Additional context**
No.

**Comment by 5HT2** [comment]
😳😳

**Comment by JerryWester** [comment]
😳 😳

**Comment by zeroeightysix** [comment]
what on earth

**Comment by zeroeightysix** [comment]
I can't reproduce this bug. What mods are you running alongside KAMI?

**Comment by omninope** [comment]
I tested further, Aura is causing this behavior.

**Comment by omninope** [comment]
Just realized Aura also break tracers.
