### ISSUE TITLE
Inconsistencies on "Block entities" target under the ESP module

### ISSUE THREAD

**Issue by omninope** [zeroeightysix/KAMI#276]
**Describe the bug**
I made a line with all the block entities in the game (accorging to the [Minecraft Wiki](https://minecraft.gamepedia.com/Block_entity)) and tried adding each one to the "Block entities" target ESP, but the results where very inconsistent. Below is the complete list of what I tested and the results:
- Beehive: The ESP didn't work;
- Bee Nest: Couldn't add as target;
- Signs: Worked fine;
- Banners: Worked fine;
- Chest: Worked fine;
- Trapped Chest: Worked fine;
- Dispenser: The ESP didn't work;
- Furnace: The ESP didn't work;
- Brewing Stand: The ESP didn't work;
- Hopper: The ESP didn't work;
- Dropper: The ESP didn't work;
- Shulker Box: Worked fine;
- Barrel: The ESP didn't work;
- Smoker: The ESP didn't work;
- Blast Furnace: The ESP didn't work;
- Campfire: The ESP didn't work;
- Lectern: The ESP didn't work;
- Beacon: The ESP didn't work;
- Spawner: Couldn't add as target;
- Jukebox: The ESP didn't work;
- Enchanting Table: Worked somewhat fine, only the book rendered as ESP, but that is the "entity" part of the block anyways;
- End Portal: The ESP didn't work;
- Ender Chest: Worked fine;
- Head: Couldn't add as target;
- Command Block: The ESP didn't work;
- End Gateway: The ESP didn't work;
- Structure Block: The ESP didn't work;
- Jigsaw Block: The ESP didn't work;
- Daylight Sensor: The ESP didn't work;
- Comparator: The ESP didn't work;
- Bed: Worked fine;
- Conduit: Worked fine;
- Bell: Worked fine.

*The "Couldn't add as target" probably means I'm stupid and not a real problem.

**To Reproduce**
1. Build KAMI;
2. Enable ESP;
3. Using the list provided above, add all block entities that had problems to the "Block entities" target ESP;
4. The ESP don't work.

**Expected behavior**
That the ESP works on all block entities.

**Screenshots**
The line of block entities. Notice many of them don't show any ESP:
![2020-10-05_20 52 45](https://user-images.githubusercontent.com/69328977/95143640-18427800-0766-11eb-8f54-307401e2aa86.png)

Same as above just from behind so the ESP's become more visible:
![2020-10-05_20 52 53](https://user-images.githubusercontent.com/69328977/95143650-1e385900-0766-11eb-8ab6-387be17416c5.png)

The ESP settings:
![2020-10-05_20 53 45](https://user-images.githubusercontent.com/69328977/95143654-21cbe000-0766-11eb-9f99-dac614ab61b0.png)

**Environment**
Did you build KAMI yourself? If so, on what commit? If not, which release did you download?
Build, commit: 5995bf76ecf7d6df52a7180749c4b17f93b1bae1

What operating operating system?
`uname -a` gives: `Linux debian 5.7.0-3-amd64 #1 SMP Debian 5.7.17-1 (2020-08-23) x86_64 GNU/Linux`.

What version of java?
`java -version` gives: `Java(TM) SE Runtime Environment (build 1.8.0_221-b11)`.

**Additional context**
No.

**Comment by zeroeightysix** [comment]
This is because minecraft doesn't actually render most of these block entities as entities, but as solid blocks - only those that require 'special care' (chest animations, bell animations, sign text rendering, enchanting table animated book, etc) are included in the pass that the `Block entities` target searches for.

You'll need to add these blocks to the `Blocks` target - they should work fine there.

Unless you have a very viable solution, this is a wontfix.

**Comment by omninope** [comment]
> add these blocks to the `Blocks` target 

I've actually already done that with some block entities, even before opening this issue, but there was so much weird behavior that I tought using the correct target for the block entities would solve it, which was not the case, hence this issue was opened.

> they should work fine there.

Right ... about that ...

I added to the "Blocks" target the block entities listed before, but only those that had problems while in the "Block entities" target. Below is the updated list:
Used the same build as before to test this.

- Beehive: Worked fine;
- Bee Nest: Worked fine;
- Dispenser: Worked fine;
- Furnace: Worked fine;
- Brewing Stand: The ESP only works on the 3 squares that hold the potions, and can only be seen from below;
- Hopper: Renders ESP only for the top part when seen from the side and some weird layers when seen from below;
- Dropper: Worked fine;
- Barrel: Worked fine;
- Smoker: Worked fine;
- Blast Furnace: Worked fine;
- Campfire: Doesn't render ESP from above and renders weirdly from the side;
- Lectern: Renders only the bottom part with ESP, doesn't render ESP from above;
- Beacon: The ESP didn't work;
- Spawner: Worked fine;
- Jukebox: Worked fine;
- Enchanting Table: Only the solid block-like part rendered the ESP, which is fine, but it also doesn't render ESP from above;
- End Portal: The ESP didn't work;
- Head: The ESP didn't work;
- Command Block: Worked fine;
- End Gateway: The ESP didn't work;
- Structure Block: Worked fine;
- Jigsaw Block: Worked fine;
- Daylight Sensor: Doesn't render ESP from above;
- Comparator: Doesn't render ESP from above.

As you can see in the list, there are 11 block entities with weird ESP rendering, or none at all, when added to the "Blocks" target. Below are low quality screenshots of those:
In order from left to right: Brewing stand, hopper, campfire, lectern, beacon, enchanting table, end portal, head, end gateway, daylight sensor and comparator.

Side view:
![2020-10-06_19 54 17](https://user-images.githubusercontent.com/69328977/95269479-feb63480-0828-11eb-88e6-bb12d280377a.png)

From below:
![2020-10-06_19 54 28](https://user-images.githubusercontent.com/69328977/95269492-04137f00-0829-11eb-8a7e-bc1dcfe382e9.png)

From above:
![2020-10-06_19 57 52](https://user-images.githubusercontent.com/69328977/95269498-07a70600-0829-11eb-909b-4a348de50fe8.png)

Any idea if this is worth the effort to try fixing? I mean, in my opinion stuff like hoppers, end portals, heads and end gateways are useful to have a nice working ESP but the rest not so much.
