### ISSUE TITLE
Optifabric makes it crash

### ISSUE THREAD

**Issue by sauceaple** [zeroeightysix/KAMI#286]
When I use optifabric with KAMI it crashes

**To Reproduce**
Install optifabric with KAMI and open Minecraft

**Expected behavior**
Launching mc

**Environment**
Did you build KAMI yourself? If so, on what commit? If not, which release did you download?
This one https://github.com/zeroeightysix/KAMI/actions/runs/329301766

What operating operating system?
Windows 10

What version of java?
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

**Additional context**
I need optifabric for CIT for my texture pack.

**Comment by 5HT2** [comment]
CIT as in connected textures?

**Comment by JerryWester** [comment]
Leaving this here: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by 5HT2** [comment]
Faster then me

**Comment by sauceaple** [comment]
Ive tried that before the NBT mod crashes

**Comment by JerryWester** [comment]
*CBT? Crashes with KAMI?

**Comment by 5HT2** [comment]
Well you didn't make any bug reports in their repos...

**Comment by sauceaple** [comment]
no its custom item models i dont need connected textures

**Comment by JerryWester** [comment]
Tried this?: https://github.com/Linguardium/ItemNbtModels/releases

**Comment by sauceaple** [comment]
Thats the one that crashed

**Comment by 5HT2** [comment]
Again, **I don't see a bug report on your GitHub profile for that mod**

**Comment by sauceaple** [comment]
I just made one I just want to know if they can get optifabric to work

**Comment by 5HT2** [comment]
I don't understand why you need Optifabric. Even the creator of Optifabric said don't use Optifabric

**Comment by JerryWester** [comment]
OptiFabric is unsupported. No one ~~with half a brain-cell~~ is going to try to intentionally make it compatible

**Comment by zeroeightysix** [comment]
Either way, duplicate of #248
