### ISSUE TITLE
"Breadcrumbs"/Trail Module

### ISSUE THREAD

**Issue by JerryWester** [zeroeightysix/KAMI#289]
**Is your feature request related to a problem? Please describe.**
When using Baritone, it's easy to get lost and forget where you came from.

**Describe the solution you'd like**
KAMI Blue has a feature where it leaves a trail behind (by placing points and rendering lines between them). This makes it easier to find where you originally came from.

**Describe alternatives you've considered**
You could use Baritone to pathfind back to a waypoint, but it may break blocks you don't want broken.

**Additional context**
N/a

**Comment by 5HT2** [comment]
> Aristois has a feature

Why not KAMI Blue as an example :roll_eyes:

**Comment by 5HT2** [comment]
https://cdn.discordapp.com/attachments/634012886930423818/741485106073436210/breadcrumbs.mp4

**Comment by JerryWester** [comment]
Sorry, I never used KAMI Blue 😅
