### ISSUE TITLE
Issue When Opening Chat in 1.16.4

### ISSUE THREAD

**Issue by humboldt123** [zeroeightysix/KAMI#292]
When you hit any button that opens chat; by default `T` or `/` the game crashes.

Error: 
[crash-2020-11-04_17.44.26-client.txt](https://github.com/zeroeightysix/KAMI/files/5491442/crash-2020-11-04_17.44.26-client.txt)

**Comment by 5HT2** [comment]
my bad

**Comment by humboldt123** [comment]
Could you explain why?

**Comment by 5HT2** [comment]
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field slashRequired was not located in the target class net.minecraft.class_4717. Using refmap KAMI-refmap.json

KAMI's command system Mixin for command previews fails on 1.16.4 due to the class being refactored and the field just missing.
