### ISSUE TITLE
Attempting to bind ClickGui before running setup wizard results in a crash 

### ISSUE THREAD

**Issue by 5HT2** [zeroeightysix/KAMI#293]
**Describe the bug**
Attempting to bind ClickGui before running setup wizard results in a crash 

**To Reproduce**
1. Run `.bind clickgui u`
2. Observe crash

**Expected behavior**
Binding works properly and it does not crash

**Environment**
Intellij, latest commit, Arch x64

**Additional context**
```
curl https://paste.ee/r/plJUO/0
```

**Comment by zeroeightysix** [comment]
Oops, this was caused by a bug unrelated to the wizard - should've been fixed a while ago.
