### ISSUE TITLE
No-FOV-Change function for NoRender module

### ISSUE THREAD

**Issue by LordMZTE** [zeroeightysix/KAMI#296]
with this enabled, the FOV wouldn't change when doing actions like sprinting

**Comment by JerryWester** [comment]
I believe no FOV is already a built-in video option, why add it to NoRender?

**Comment by LordMZTE** [comment]
I didn't know that was a thing... It's strange that so many utility mods do that

**Comment by JerryWester** [comment]
I'm pretty sure it was a recent change (1.15 added it IIRC), so I can understand the confusion
