### ISSUE TITLE
Baritone status variable for text widgets

### ISSUE THREAD

**Issue by LordMZTE** [zeroeightysix/KAMI#297]
this would work semilar to impact's overlay by showing what baritone is doing. for example `Pathing to X Y Z` or `Mining BlockOptionalMeta {minecraft:diamond_ore}`

**Comment by 5HT2** [comment]
`BaritoneUtils.INSTANCE.getPrimary().getPathingControlManager().mostRecentInControl().get().displayName()` is the syntax in Java for this

**Comment by LordMZTE** [comment]
oops, forgot to close this even tho my pr with it got merged
