### ISSUE TITLE
No walking screenshake option for NoRender

### ISSUE THREAD

**Issue by LordMZTE** [zeroeightysix/KAMI#299]
when walking the stream shakes. it would be nice to be able to disable that.

**Comment by zeroeightysix** [comment]
Disable view bobbing in video options.

**Comment by LordMZTE** [comment]
sorry :P i should check the game for options i don't know about i guess. the reason i'm suggestion this is that most utility mods have an option like this which is redundant i guess

**Comment by 5HT2** [comment]
> redundant 

Because most are on older versions, which didn't add it natively into the game :p
