### ISSUE TITLE
[Feature] nbt command

### ISSUE THREAD

**Issue by LordMZTE** [zeroeightysix/KAMI#313]
The `nbt` command would print the NBT data of the entity/block the player is looking at into chat. This could be used for finding out which Player owns a pet and so on. This cannot be done in vanilla, as the `data get` command which would behave the same requires permissions, although the NBT data is available on the client too.

**Comment by zeroeightysix** [comment]
Even cooler would be a GUI window for this :eyes:

**Comment by LordMZTE** [comment]
That would mean somehow Rendering an imgui without having the click gui open right? Sounds painful to implement

**Comment by LordMZTE** [comment]
I don't think it would be that useful either, as the user can copy the output from the console and view it in an editor of their choice

**Comment by zeroeightysix** [comment]
> That would mean somehow Rendering an imgui without having the click gui open right? Sounds painful to implement

KAMI is already capable of this. NBT is a tree - a GUI window that can search in and easily navigate the NBT tree would be useful. It could also be extended to inspect the NBT of items in your inventory, chat NBT, etc. If a more abstract implementation is made, it could also function as a 'inspect' window for individual packets in a packet sniffer.

Obviously you also can just invoke a command that opens a window in the GUI, and then _just open the GUI_ to inspect the NBT.

**Comment by LordMZTE** [comment]
my PR implementing this got merged :D
