### ISSUE TITLE
Aura specifies nametag

### ISSUE THREAD

**Issue by AlexandreFinne** [zeroeightysix/KAMI#316]
For certains farms, we have mob with nametags that we need to keep.
Is it possible for the Aura module to specifiy to not attack mobs with nametags ?

**Comment by 5HT2** [comment]
No, it's not possible. You can make a suggestion, following the proper issue template.

**Comment by zeroeightysix** [comment]
Now you can.

**Comment by LordMZTE** [comment]
damn. i expected someone to open a 5 line PR and then go through a 1-month review period
