### ISSUE TITLE
Keybinds don't allow key modifiers

### ISSUE THREAD

**Issue by zeroeightysix** [zeroeightysix/KAMI#36]
Keybinds should allow key modifiers. (e.g. binding sprint to ctrl+s)

**Comment by wine** [comment]
What about multi-key combinations by using a List so you can bind Sprint to e.g. `ctrl+alt+s`

Maybe also support cased/lowercase so you can bind Sprint to e.g. `ctrl+alt+S` and Killaura to `ctrl+alt+s`

**Comment by zeroeightysix** [comment]
Implemented in #40

**Comment by wine** [comment]
Would be nice if binds would support multiple keys such `ctrl+a+home` for a module

**Comment by zeroeightysix** [comment]
Hmm, I'm against this.
Two reasons:
* It totally goes against convention. Where have you ever seen keybinds act like this? Almost always it's just `modifiers + some key`.
* It would make pressing keybinds incredibly awkward and inconvenient
  * Keybinds are only processed upon releasing a key: otherwise binds like `ctrl+a` and `ctrl+a+home` would overlap

**Comment by wine** [comment]
Fair point, I guess we can close this now.
