### ISSUE TITLE
Fix sloppy features

### ISSUE THREAD

**Issue by zeroeightysix** [zeroeightysix/KAMI#4]
KAMI has a few half-assed features which I'd like to see fixed. I'll be using this issue as a to-do list and it can function as inspiration for potential contributors.
- [x] Brightness sometimes leaves the brightness setting high after closing, enabling permanent brightness
- [x] The build.gradle is a horrible mess, fix it
- [x] Chams needs a proper implementation
- [x] Fix NoEntityTrace
- [x] Fix TpsSync
- [x] Nametags needs prettier item rendering + enchantments

Feel free to leave comments for feedback or to notify me if you're willing to work on something.

**Comment by wine** [comment]
See https://github.com/zeroeightysix/KAMI/pull/5 for brightness

**Comment by ChristoferMinestar** [comment]
Implement `Module#getDescription` to show description on hover in GUI

**Comment by S-B99** [comment]
Close this since the pr for brightness has been merged?

**Comment by zeroeightysix** [comment]
> Close this since the pr for brightness has been merged?

Nope, we still need prettier nametags

**Comment by S-B99** [comment]
Oop sorry missed that

**Comment by dominikaaaa** [comment]
If I ever get around to the last issue I linked ^ then I'd be happy to port this to KAMI
