### ISSUE TITLE
.bind clickgui rshift doesnt work

### ISSUE THREAD

**Issue by sadboys2001** [zeroeightysix/KAMI#42]

**Comment by ChristoferMinestar** [comment]
Have you tried right-shift?

**Comment by zeroeightysix** [comment]
RSHIFT is the correct identifier for right shift. It just indeed, does not toggle when right shift is pressed. I'll look into it.

**Comment by zeroeightysix** [comment]
Oh. Silly me: shift is a modifier key, so why wouldn't right shift be? This is a unavoidable side effect of having keybinds with modifiers.
