### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by wine** [zeroeightysix/KAMI#45]
Would be really neat if we could have a plugin system which would load compiled jar artifacts.

This would also of course help slimming down the client to a very minimal client where users can easily create what they want using a plugin API, hosted on a Maven server.

We can expose things such as the feature, command and event system to the plugins so they can register features, commands and events. We should though **not** expose things like the (if any) account manager since the plugin shouldn't need to use it.

Another idea could be exposing through a manifest file, so the user can choose what systems are exposed to the plugin, this way you are aware that the plugin might use that system.

**Comment by EmotionalLove** [comment]
https://github.com/EmotionalLove/Adorufu_Client/tree/master/src/main/java/com/sasha/adorufu/api

Adorufu has a good example of this, and it has a working (but hacky) way to allow the developer to interact with minecraft functions.

**Comment by zeroeightysix** [comment]
Barebones plugins have been implemented in KAMI. They are separate fabric mods that are expected to register themselves to kami, so a permissions system is absent - the user is liable when installing plugins to check if they are trustworthy.
When, and if, I do implement some GUI elements for managing installed plugins, I'll make sure that the dangers of plugins are highlighted.
