### ISSUE TITLE
Option for changing colors, including a non rainbow option for array list

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#46]
## Expected behavior
Color picker

## Actual behavior
No color picker

## Steps to reproduce the problem

  1. Open GUI
  2. Open every menu
  3. Don't see a color picker 😋

## Specifications

  - Version: b9 latest build
  - Platform: Win10 x64

**Comment by wine** [comment]
You don't have to use the template if the issue isn't a bug, just explain what & why you want it.

**Comment by ChristoferMinestar** [comment]
@wine I realised that after

**Comment by zeroeightysix** [comment]
To be implemented in #51

**Comment by wine** [comment]
See #51, this is already planned for the GUI rework
