### ISSUE TITLE
Intercept chat messages

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#47]
So an option to intercept your chat message, for example, warn you if it contains the word /kill.

This is very edge case, but there is a good reason for it: https://cdn.discordapp.com/attachments/496724197121196033/499677661803708416/unknown.png (contains profanity)

**Comment by zeroeightysix** [comment]
Honestly, you should just know yourself what commands you execute and which you don't. This seems like a lot of work for something you can easily prevent by thinking before you press enter.
