### ISSUE TITLE
Add center option for visible modules

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#48]
As well as align left, align right. Also, an option to move the module itself quickly to the opposite side/height would be great.

Already has the best UI out there, though!

**Comment by zeroeightysix** [comment]
You already can change the alignment of modules by smashing the window against the sides of your window. For example, if the active modules window reaches x0 the alignment changes to left. I don't really see a purpose for center alignment, but this could be implemented along with the new UI.

**Comment by ChristoferMinestar** [comment]
Thanks!
