### ISSUE TITLE
When switch between flight modes you are able to still fly when feature disabled.

### ISSUE THREAD

**Issue by h4rmy** [zeroeightysix/KAMI#502]
**Describe the bug**
You can fly with the flight function disabled

**To Reproduce**
1. Turn on flight with vanilla mode
2. Switch to packet/static mode
3. Turn off flight

**Expected behavior**
Double press spacebar and you can fly while flight turned off

**Video**
**https://youtu.be/7C_HeznSd5I**

**Environment**
Did you build KAMI yourself? **no**. Which release did you download? [this one](https://github.com/zeroeightysix/KAMI/actions/runs/413552302)
What operating operating system? **Win10 Home**
What version of java? **Java 8 update 274 64-bit**

**Comment by LordMZTE** [comment]
Looks like we don't turn off flight when the mode is switched

**Comment by h4rmy** [comment]
> Looks like we don't turn off flight when the mode is switched

this is still a bug

**Comment by JerryWester** [comment]
@h4rmy 

![](https://i.kym-cdn.com/photos/images/original/001/650/747/aaf.png)

That's why the issue is still open

**Comment by JerryWester** [comment]
> this is still a bug

This is no longer a bug
