### ISSUE TITLE
Aura not attacking mobs which takes damages in lava

### ISSUE THREAD

**Issue by AlexandreFinne** [zeroeightysix/KAMI#503]
**Describe the bug**
Aura is not attacking mobs which takes damages in lava.

**To Reproduce**
1. Activate the aura to kill all living
2. Spawn an iron golem in the lava

**Expected behavior**
Hit the golem.

**Additional context**
Even when the mobs are taking fire damages, it happens that Aura is not always attacking

**Comment by LordMZTE** [comment]
I think this is because of the Damage cooldown a mob has. The lava damages the mob and activates the cooldown before Kill Aura gets a chance to hit. This would mean that this is not really anything that can be fixed.

**Comment by 5HT2** [comment]
Could've at least closed the issue if you're going to react with :+1:

**Comment by Luna5ama** [comment]
Doesn't it have an option to not check the damage cooldown?

**Comment by LordMZTE** [comment]
> 
> 
> Doesn't it have an option to not check the damage cooldown?

It does, but that's not really helpful here
