### ISSUE TITLE
Ability to change the modlist that forge sends to the server.

### ISSUE THREAD

**Issue by charlesathon** [zeroeightysix/KAMI#511]
I think it would be useful to have an undercover mode where KAMI isn't visible on forge client side modlists. Some servers require specific mods and check that you have them and only them before you can join the server. I'm not sure if it is even possible but I found a gitlab repo claiming to be able to do it but couldn't understand it and KAMI integration would be epic in my opinion. 

https://gitlab.com/hexdiract/custom-forge-handshake

**Comment by 5HT2** [comment]
Uh, KAMI runs on Fabric, not Forge

**Comment by charlesathon** [comment]
So it does for 1.16.4. Can it not work on 1.12.2?

**Comment by charlesathon** [comment]
Or is KAMI now only on fabric?

**Comment by 5HT2** [comment]
KAMI is only supported on Fabric, the Forge version hasn't consistently been updated in about 2 years

**Comment by BitBuf** [comment]
@charlesathon The Forge version that you are referencing has been forked and continued through KAMI Blue (https://github.com/kami-blue/client ). This repository is intended for the newer Fabric KAMI.

**Comment by charlesathon** [comment]
Okay perfect. Thank you for your help
