### ISSUE TITLE
Is there a way to add KAMI to modded forge servers? I know it is a fabric mod but KAMI Blue won't be updated to 1.16.4

### ISSUE THREAD

**Issue by charlesathon** [zeroeightysix/KAMI#512]
My problem is that I want to play modded minecraft with KAMI installed client side without the server knowing that I have it installed. This is okay with fakevanillaclient on but it still isn't on the server side approved forge modlist. Is there a way to run KAMI seperately to the forge loader so I can still access the server? If not do you think there could be? Thanks

**Comment by 5HT2** [comment]
KAMI is only supported on Fabric

**Comment by charlesathon** [comment]
So there's no way to use it on a forge server?

**Comment by LordMZTE** [comment]
There is no way to use KAMI (red) on a forge server.

**Comment by BitBuf** [comment]
No version or fork of KAMI will likely ever exist on 1.16 Forge. Only Fabric and 1.12.2 Forge.

**Comment by 5HT2** [comment]
I mean there's a 1.8.9 port lol

**Comment by charlesathon** [comment]
Okay thank you

**Comment by LordMZTE** [comment]
There are KAMI alternatives that work for forge 1.16 tho

**Comment by charlesathon** [comment]
Not with as good UI

**Comment by charlesathon** [comment]
I tried wurst but couldn't find a fakevanillaclient. In your experience do you think there is any way to get a minecraft client on a modded forge server?

**Comment by LordMZTE** [comment]
I don't know what you mean with "get a minecraft client on a modded forge server"

**Comment by charlesathon** [comment]
Any way to use hacks on a forge server that has whitelisted mods? I basically need a way to edit the list that is sent from client to server so that the server only sees that I have the correct mods installed

**Comment by LordMZTE** [comment]
That probably exists, but i'm not aware of that. Let's continue this discussion on [the kami discord](https://discord.gg/9hvwgeg)

**Comment by charlesathon** [comment]
Okay will do
