### ISSUE TITLE
.give command to get all items from creative mode

### ISSUE THREAD

**Issue by LordMZTE** [zeroeightysix/KAMI#515]
This command would have a syntax of `.give <item_id>[{nbt}] [count]` and would work similarly to the normal `/give` command, but instead, it takes the items from the creative inventory (other utility mods can do this as well) but allows getting items that are not in the normal creative inventory, such as command blocks and allows giving them NBT data.

An example of this command would be `.give command_block{BlockEntityTag: {Command: "say hi"}} 64` which would give the player 64 command blocks that say "hi" when activated. Of course this only works in creative mode.

Also, I'm not sure if the NBT feature would be possible, but I think it is.

**Describe alternatives you've considered**
Can't think of any alternatives

**Comment by zeroeightysix** [comment]
You could probably, to an extent, just copy exactly what the real `give` command does.

**Comment by nekiak** [comment]
I don't know if KAMI has this, but it would be cool to have a `copynbt` command to see the nbt of existing items.

**Comment by LordMZTE** [comment]
> I don't know if KAMI has this, but it would be cool to have a `copynbt` command to see the nbt of existing items.

type `.nbt hand` to witness the beautiful nbt viewer gui I spent my time on.
