### ISSUE TITLE
Crashing on ARM macOS when entering a world

### ISSUE THREAD

**Issue by stefan2225** [zeroeightysix/KAMI#527]
**Describe the bug**
MC Client crashes with KAMI loaded when entering a world on arm64 macOS with native lwjgl (self-compiled), doesn't crash in the main menu.

**Crashlog**
https://pastebin.com/z4CKEgs6

**Expected behavior**
It loads the world without crashing and works (duh).

**Environment**
OS is macOS 11.2.1, tried the 1.16.4 version of KAMI on macOS 11.2.0 a few weeks earlier but it resulted in the same crash log.
Java version is OpenJDK 11.0.9 (latest from Homebrew)
MultiMC is being used.

**Additional context**
I'm not sure if this is just an issue with macOS in general or related to the fact that I am on a whole different architecture.

**Comment by zeroeightysix** [comment]
KAMI ships with [bindings](https://github.com/SpaiR/imgui-java) to imgui. If you'd like to use ARM with KAMI, you'll have to find a way to compile imgui and the bindings for ARM yourself.

For the time being, I don't plan on supporting ARM.

**Comment by stefan2225** [comment]
alr, thanks for answering that fast will figure it out myself.

**Comment by LordMZTE** [comment]
I guess no one expected users of KAMI to be ARMed with such unusual architectures.

**Comment by nopjmp** [comment]
I can test on an ARM MacBook Pro. You need to be using the Intel Java Library and not any arm64 versions so it will use Rosetta 2. If there is a bug in the Java GUI bindings I can look into the architectures.

Minecraft and s crashing in the LWJGL natives to be built as well. So just install the adoptopenjdk 8 or similar Java versions and select it explicitly in the /Library/JavaVirtualMachines/ directory. I'm using the Zulu versions for now for arm and adoptopenjdk for x86 so it's easy to tell.
