### ISSUE TITLE
how to open the menu?

### ISSUE THREAD

**Issue by ehbuda** [zeroeightysix/KAMI#528]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
Did you build KAMI yourself? If so, on what commit? If not, which release did you download?
What operating operating system?
What version of java?

**Additional context**

**Comment by ehbuda** [comment]
i dont have a single clue on how to open the menu any help please would be great

**Comment by JerryWester** [comment]
Please read the readme and the issue template before making an issue. https://github.com/zeroeightysix/KAMI#usage

**Comment by zeroeightysix** [comment]
It's on the 'homepage' of this repo.

![image](https://user-images.githubusercontent.com/27009727/107877060-6745aa00-6eca-11eb-802d-60e0733250df.png)

**Comment by JerryWester** [comment]
For future reference, questions like these are better for the discord. It's preferable that you read the readme first, but Discord should be used for small questions, while the issue tracker should be for reporting issues while using KAMI or suggesting new features.
