### ISSUE TITLE
language

### ISSUE THREAD

**Issue by Geon26** [zeroeightysix/KAMI#532]
i would like to ask you how to change language of the client 
Thanks for reply

**Comment by BitBuf** [comment]
What

**Comment by 5HT2** [comment]
You cannot.

**Comment by Geon26** [comment]
oh ok thanks

**Comment by 5HT2** [comment]
inb4 doesn't close their issue

**Comment by Geon26** [comment]
so the original language of the client is not English?

**Comment by 5HT2** [comment]
Yes it is.

**Comment by Geon26** [comment]
because i have this chinnese or what is it :D

**Comment by 5HT2** [comment]
What??

**Comment by Geon26** [comment]
i installed the client and joined the server, when i joined i opend the gui and i thing there was some settings but it was all in Chinnese

**Comment by 5HT2** [comment]
You didn't install KAMI then

**Comment by Geon26** [comment]
but now i tried again and it is English, so it was probably a bug

**Comment by 5HT2** [comment]
There isn't any type of bug that just magically translates everything into Chinese....

**Comment by Geon26** [comment]
idk what was it if it happens again i can take screenshot

**Comment by nopjmp** [comment]
There is a rendering bug with the GUI right now that I'm trying to track down in my free time. It's not Chinese, it's a graphical glitch. You'll notice that the rendering isn't how it's supposed to be and it's not actually Chinese characters but graphical artifacts.

This happened a while ago on the old kg/imgui implementation but we just have to put more safe guards in place on the new implementation.

**Comment by 5HT2** [comment]
I assumed they meant literal Chinese :moyai:

**Comment by Geon26** [comment]
That would make sence
