### ISSUE TITLE
Graphical Glitches in ClickGUI (ImGui)

### ISSUE THREAD

**Issue by nopjmp** [zeroeightysix/KAMI#533]
Currently, what appears to be what looks to be a GL initialization oddity. I think 086 might have more information on this because it's happened before with text rendering. I think a VBO or another cached resource is getting corrupted on start/initialization.

I'll update my issue with a screenshot if I can get one again. It doesn't seem to happen when debugging probably due to the latency of the debug communication delaying something just enough for it to work.

**Comment by zeroeightysix** [comment]
It's an incredibly strange bug and I was never able to track down _why_ it happens.

There's a (still open) issue about it on the kotlin-graphics repo, https://github.com/kotlin-graphics/imgui/issues/114.

There is only one time at which I was able to reproduce it 100% of the time, which was while developing Nametags:

- If the module is enabled **while imgui init happens**
- And the rendering happens **before** imgui render, in the same render cycle

Then the rendering was always moonrunes. See [this comment](https://github.com/zeroeightysix/KAMI/blob/bd5d01b0c81bfe23bd93838022287c8d6e55a7ca/src/main/kotlin/me/zeroeightsix/kami/feature/module/Nametags.kt#L92).

I'd love to know why it has returned. It seems certain people (including myself) don't even ever get it.
