### ISSUE TITLE
Baritone integration not working

### ISSUE THREAD

**Issue by redstonekasi** [zeroeightysix/KAMI#537]
**Describe the bug**
Baritone integration isn't working.

**To Reproduce**
1. Install [latest baritone for fabric](https://github.com/cabaletta/baritone/releases/tag/v1.6.3).

**Expected behavior**
The baritone menu is supposed to appear in the ClickGUI and the `#come` command in baritone doesn't work.

**Screenshots**
![Screenshot from 2021-03-04 12-49-00](https://user-images.githubusercontent.com/42352565/109959943-727d4000-7ce8-11eb-940c-dd9068f0d55b.png)

**Environment**
**Commit**: bd5d01b
**Operating system**: Manjaro Linux
**Java version**: 1.8.0_282

**Additional context**
**Log**: https://paste.redstonekasi.de/?72f26f41b80b6088#7j45GPYEbbaveek1pkMqqGA7XVdBTpUYMz1Wturvni5W

**Comment by 5HT2** [comment]
Which jar did you use?

**Comment by redstonekasi** [comment]
You can see in the log, I believe it's `baritone-api-fabric-1.6.3`

**Comment by zeroeightysix** [comment]
Should be fixed in b4c57f8be9e12183bdcd26e13024b971b391d73f . Can you give this commit a try? If it works, I can merge it to `fabric` and close this issue.

**Comment by redstonekasi** [comment]
It's kinda working. The baritone menu is now there, but the #come command doesn't work yet.

**Comment by zeroeightysix** [comment]
Good enough for me. The official baritone builds are obfuscated, and the come command requires a mixin (into baritone) to work. I'm not interested in remapping for baritone, so, unless someone opens a PR to fix this - it will stay that way.
