### ISSUE TITLE
Showing plugins 

### ISSUE THREAD

**Issue by Dziondzio** [zeroeightysix/KAMI#544]
**Describe the bug**
Not working on 1.16.5 

**Environment**
Official for fabrric
What operating operating system? Windows 10
What version of java? Newest

**Comment by zeroeightysix** [comment]
Please re-open with more information.

What is not working? KAMI does not yet have a feature to show plugins in any UI.

**Comment by Dziondzio** [comment]
![image](https://user-images.githubusercontent.com/60745691/114779173-104b3c80-9d76-11eb-9c31-6782063ca11c.png)
 so what is this command?

**Comment by zeroeightysix** [comment]
> so what is this command?

KAMI has very simple support for plugins. They come in the form of other fabric mods that depend on KAMI and register themselves to KAMI as a plugin. Currently, no useful plugins exist you can download. If there were a plugin loaded, it would show up in the list of possible arguments for `plugin enable` and `plugin disable`.

**Comment by Dziondzio** [comment]
i have it on "." and arguments .plugins enable  / disable
