### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SolsticeSpectrum** [zeroeightysix/KAMI#547]
It would be pretty cool if KAMI-Blue features were ported over KAMI since it has been archived. I mean not all of them, that would probably not be possible anyway but the interesting ones. Btw I still hope for RemoteCommands to be implemented one day.

**Comment by zeroeightysix** [comment]
Issues serve to track the development of one feature, bug, etc. This is a scope far too broad to be a good issue.

People are welcome to port over features from KAMI Blue (preferably, provided the authors of those features are okay with its porting) - but I feel like this issue servers no purpose to attaining that goal.
