### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by garv-shah** [zeroeightysix/KAMI#548]
**Describe the bug**
Crash on Startup

**To Reproduce**
Steps to reproduce the behaviour:
2. Download the latest archive from actions
3. Try and run the game
4. Witness a crash

**Expected behaviour**
The game loading without crashing

**Environment**
Did you build KAMI yourself? If so, on what commit? If not, which release did you download?
[I used this release](https://github.com/zeroeightysix/KAMI/actions/runs/696003182), KAMI-1.16.5-mar

What operating operating system?
MacOS Big Sur 11.3.1, Apple Silicon

What version of java?
11.0.9.1, Azul Systems, aarch64

**Additional context**
The problem persists without the ARM 64-bit JDK as well, as I tested with AdoptOpenJDK OpenJ9 11, running Minecraft through Rosetta.
I also use the [m1-multimc-hack](https://github.com/yusefnapora/m1-multimc-hack) to get Minecraft running natively. As I said, the problem still persists running "normally"
Crash with running Minecraft natively: [crash-2021-05-10_22.55.54-client.txt](https://github.com/zeroeightysix/KAMI/files/6481623/crash-2021-05-10_22.55.54-client.txt)
Crash with running Minecraft through Rosetta "normally": [crash-2021-05-15_10.32.33-client.txt](https://github.com/zeroeightysix/KAMI/files/6481639/crash-2021-05-15_10.32.33-client.txt)

**Comment by JerryWester** [comment]
Known issue, #527 

EDIT: For clarification on why this happens, one of the libraries KAMI uses is pre-compiled for amd64 systems. It would have to be recompiled for your specific processor architecture.

**Comment by garv-shah** [comment]
ah okay thank you very much!
