### ISSUE TITLE
KAMI is crashing while 1.16.5 optifabric

### ISSUE THREAD

**Issue by brolyxd123** [zeroeightysix/KAMI#551]
When i try to run kami with optifabric 1.16.5 its crashes every time.. how i can use optifine with kami?

1. Setup opti-fabric v1.9.2 in mods folder
2. Setup optifine 1.16.5 hd gu7 in mods folder
3. Setup kami too
4. launch andSee error

Did you guys know any other ways to setup optifine with kami???

**Comment by JerryWester** [comment]
Duplicate, #248
