### ISSUE TITLE
ADD AIM-ASSIST too PLEASE.

### ISSUE THREAD

**Issue by brolyxd123** [zeroeightysix/KAMI#552]
Yeah aura is good but i need aim-assist too :( , I must to play legal.

**Comment by JerryWester** [comment]
If you want to play fairly, then why are you using mods at all?

**Comment by brolyxd123** [comment]
> If you want to play fairly, then why are you using mods at all?

i spelt it wrongly , i meant "i wanna play legit" but aura is you know non legit.

If creator wants too i wish i can see aim assisst to please...

**Comment by zeroeightysix** [comment]
KAMI is a utility mod aimed at anarchy servers, thus its features are geared towards that meta.

I do not condone its use on servers outside of that scope. Aim assist would be useless on anarchy servers (where blatant cheating is the norm). I will not be adding this module for that reason.
