### ISSUE TITLE
Storage ESP issues with Impact + KAMI

### ISSUE THREAD

**Issue by GreastTT2** [zeroeightysix/KAMI#555]
I just downloaded both forge files, one are Impact 4.9.1 and KAMI blue. So, both of this working great! But for impact there is a module called Storage ESP and Search, so basically they have feature to change colors in shalkers, chests, enderchests and so on. But KAMI blue makes disable this feature and makes it only gray color.
![image](https://user-images.githubusercontent.com/63648841/121825820-72df8c80-cc82-11eb-9140-de85a58f329e.png)

Here is the setting: 
![image](https://user-images.githubusercontent.com/63648841/121825833-8ee32e00-cc82-11eb-87bc-fe0eb56511fe.png)

How can I fix this visual problem?

**Comment by JerryWester** [comment]
Unfortunately, this isn't KAMI Blue. KAMI Blue has been discontinued, and you won't see any support for it.

**Comment by GreastTT2** [comment]
> 
> 
> Unfortunately, this isn't KAMI Blue. KAMI Blue has been discontinued, and you won't see any support for it.

Thanks for answer. Really sad to hear that, that both hacks are really comfortable with each other. Really sad.
