### ISSUE TITLE
Autoeat interacts with blocks

### ISSUE THREAD

**Issue by sadboys2001** [zeroeightysix/KAMI#56]
## Expected behavior
Eat the food and not interact with e.g shulkers when facing them.

## Actual behavior
Repeatedly opens the shulker while trying to eat.

**Comment by blockparole** [comment]
ugly lazy fix idea: send start sneak packet prior and end sneak packet after eating

**Comment by S-B99** [comment]
I pointed out in my issue a better way to do this would be to tell the game to use the item instead of emulating a right click

**Comment by dominikaaaa** [comment]
Dew figured out how to fix it, look at the commit if you're interested in the fix :p

**Comment by dominikaaaa** [comment]
We fixed this in blue, as you can see in the above commit. It looks like this shouldn't happen in Fabric anymore?
```kotlin
            mc.player.setCurrentHand(Hand.OFF_HAND);
            eating = true;
            KeyBinding.setKeyPressed(((IKeyBinding) mc.options.keyUse).getBoundKey(), true);
            ((IMinecraftClient) mc).callDoAttack();
```

**Comment by zeroeightysix** [comment]
> It looks like this shouldn't happen in Fabric anymore?

I'll test it.
