### ISSUE TITLE
Latest build of kami crashes with future

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#60]
## Steps to reproduce the problem

  1. Have Future and Kami in `\.minecraft\mods\1.12.2`
  2. Launch
  3. See a crash
  4. Try again without Future
  5. Game launches normally

Might be related to re-write, which is the main big change when switching versions
Or it might be related to #31 

## Specifications

  - Version: Latest build as of October 14th
  - Platform: Windows 10 x64

## Logs
**EDIT:** Logs removed
[debug.log](https://github.com/zeroeightysix/KAMI/files/2476967/debug.log)
[latest.log](https://github.com/zeroeightysix/KAMI/files/2476968/latest.log)

**Comment by ChristoferMinestar** [comment]
Update: I sent wrong logs, as for some reason the client did not generate logs with crash with Kami + Future. When I get home I will look into why it won't generate logs.

**Comment by ChristoferMinestar** [comment]
## New update: 
@zeroeightysix send a quick and dirty patch which disables the injecting mechanism of safewalk which future doesn't like, so this is a temporary fix, that works. In effect safewalk doesn't work.

## The jar:
[KAMI-b9-release-custom-fix.jar.gz](https://github.com/zeroeightysix/KAMI/files/2479750/KAMI-b9-release-custom-fix.jar.gz)
(zipped, need to extract first)

**Comment by ZeroMemes** [comment]
Lol this literally shouldn't have been closed. The custom fix that @ChristoferMinestar provided literally said:

> [...] so this is a temporary fix, that works.

This issue should either be **resolved** or marked as **won't resolve**.

**Comment by ChristoferMinestar** [comment]
@zeromemes, I closed this because the goal is now not to solve why Kami is crashing with Future, but what can we do to fix this.
