### ISSUE TITLE
Rewrite the way safewalk works to avoid future complications and current ones.

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#61]
Currently, afaik, safewalk hooks into Minecraft, and Future really doesn't like that. A rewrite to not require a hook would be great.

This could also solve in effect #31

**Comment by zeroeightysix** [comment]
As far as I'm aware (of what 0x22 told me) this is a future bug - you'll have to wait for the next future update for this to be solved. It'd be silly for me to write a workaround if it's already fixed on future's end.
