### ISSUE TITLE
When building, the gradel reverts changes (baritone branch only)

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#65]
Ugh I have spent over an hour testing this trying to get baritone to work. 
So, when you build, either manually or using autobuild, the `MixinEntity.java` file gets reverted back to [this](https://pastebin.com/NGuAGdKP), even though it looked like [this ](https://pastebin.com/itxShWLc)(saved, ofc) before I built it.
Edit to clarify: by reverted I mean it reverts the file to before **I** made changes.

Note: this only happens with the Baritone branch.
This is required for me to use Kami with Future because the change disables hooking which interferes with 5zig and Future

**Comment by EmotionalLove** [comment]
try doing @Mixin(value = Entity.class, priority = 998)

**Comment by zeroeightysix** [comment]
This is odd.. doesn't appear to be happening for me. Anyone else experiencing this?

**Comment by ChristoferMinestar** [comment]
I will have time to test in an hour or 2. @emotionallove said it could be gradel cache, and I did build once before editing, and after editing building didn't save edits so it could be that

**Comment by wine** [comment]
> gradel cache

It's Gradle not Gradel

**Comment by ChristoferMinestar** [comment]
Update: I just redownloaded, did edit right away, then built. It worked fine now.
