### ISSUE TITLE
Baritone Branch crashes with only Kami installed

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#67]
## Steps to reproduce the problem

  01. Delete .minecraft
  02. Launch clean install of Forge
  03. It works.
  04. Build master branch
  05. Copy it to the mods\1.12.2 folder
  06. Launch and see it works perfectly
  07. Delete .minecraft
  08. Launch clean install of Forge
  09. Build the baritone branch
  10. Copy it to the mods\1.12.2 folder
  11. Launch and see a crash

## Specifications

  - Version: Latest build as of October 21st
  - Platform: Win10 x64
  - Forge: Latest as of October 21st

## Logs:

Master branch build:
[2018-10-21-1.log.gz](https://github.com/zeroeightysix/KAMI/files/2499381/2018-10-21-1.log.gz)
[debug-1.log.gz](https://github.com/zeroeightysix/KAMI/files/2499382/debug-1.log.gz)

Baritone branch build:
[debug.log](https://github.com/zeroeightysix/KAMI/files/2499384/debug.log)
[latest.log](https://github.com/zeroeightysix/KAMI/files/2499385/latest.log)

No crash logs were produced even though the launcher detected a crash

**Comment by ChristoferMinestar** [comment]
Update: Sasha said she has the same issue and crash, and she will provide a hotfix.

This is not a Kami issue, as building `baritone-standalone-1.0.0-hotfix-2.jar` yourself and using just that causes the crash.

**Comment by EmotionalLove** [comment]
> Update: Sasha said she has the same issue and crash, and she will provide a hotfix.
> 
> This is not a Kami issue, as building `baritone-standalone-1.0.0-hotfix-2.jar` yourself and using just that causes the crash.

https://github.com/zeroeightysix/KAMI/pull/68 here ya go :innocent:

**Comment by ChristoferMinestar** [comment]
Forgot: [here](https://github.com/cabaletta/baritone/issues/232) is the issue in baritone's GitHub. Hopefully they will provide a proper fix.

**Comment by leijurv** [comment]
fam you were using `KAMI-feature-baritone-impl-b9-release.jar` not `baritone-standalone-1.0.0-hotfix-2.jar`
