### ISSUE TITLE
Feature: Rich Presence for Discord with server IP

### ISSUE THREAD

**Issue by dominikaaaa** [zeroeightysix/KAMI#72]
**Describe the solution you'd like**
A rich presence for Discord that reports time played, server IP.

**Describe alternatives you've considered**
Adorufu, but Kami is still better.
**Additional context**
Something Like this: 
![image](https://user-images.githubusercontent.com/17222512/47505599-722d2a00-d83c-11e8-87cd-b27d0f4cd8d5.png)

**Comment by ZeroMemes** [comment]
The information that is displayed by rich presence should be configurable.

**Comment by dominikaaaa** [comment]
I currently use [MinnDevelopment/discord-rpc-release](https://github.com/MinnDevelopment/discord-rpc-release) but [Vatuu/discord-rpc](https://github.com/Vatuu/discord-rpc) appears to be actively maintained and is used by Nuker, so you could ask him questions

**Comment by humboldt123** [comment]
I can do this!

**Comment by humboldt123** [comment]
@zeroeightysix close the issue this was resolved.
