### ISSUE TITLE
Fading brightness option

### ISSUE THREAD

**Issue by ZeroMemes** [zeroeightysix/KAMI#77]
The brightness module should support brightness fade in/out, and the speed of the fade effect should be configurable.

**Comment by wine** [comment]
Maybe support different transition effects aswell?

**Comment by zeroeightysix** [comment]
@wine transition effects?? linear or exponential fading
That's quite silly!

**Comment by Mhowser** [comment]
customization is always welcomed!

**Comment by zeroeightysix** [comment]
> customization is always welcomed!

Of course, but I like keeping an even balance between effort I put into a feature and the actual use of that feature. Multiple "transition effects" seems like a hassle to implement and 99% of users wouldn't even have a darn clue what they do.

**Comment by Mhowser** [comment]
I understand that. I would love to help out with adding new features and such but I dont know enough to start coding..

**Comment by zeroeightysix** [comment]
Ended up implementing your silly transitions anyways. Hope they work well, wasn't really able to see a difference between bad transitions and 3 fps on this laptop..

**Comment by Mhowser** [comment]
Thank you for doing this! We appreciate the effort 😀
