### ISSUE TITLE
Kami (baritone branch) + Future autowalks for no reason.

### ISSUE THREAD

**Issue by S-B99** [zeroeightysix/KAMI#78]
**Describe the bug**
So when both are loaded, it will walk forward, unless you turn on reverse autowalk in Kami. Then, not as if its counteracting pressing W, but as if it stopped going forward it goes backward.

This only happens with the baritone branch.

**To Reproduce**
1. Test Future and Kami separately. They both work fine.
2. Now launch both, and open a game
3. It walks forward even if autowalk is turned off in both Future and Kami, and no path has been set in Baritone
4. Try setting autowalk in Kami to reverse and toggle it with a keybind. 
5. Notice it stop walking for a split second. Then it reverses the walking. This proves its something in Kami that's messing with Future.

**Additional context**
Please note: I had to modify the jar in order to run it with future due to #61 
How I modified it: 
Inside `KAMI/src/main/java/me/zeroeightsix/kami/mixin/client/MixinEntity.java` delete lines `30` to `34`
Now build and observe that it doesn't crash with future. This is a workaround, and shall be fixed eventually.

**Files**
My modified jar incase people can't reproduce but they can with my jar (in which case this should be closed and I need the jar that works properly with Future): 
[KAMI-feature-baritone-impl-10-25-01-future-b9-release.jar.zip](https://github.com/zeroeightysix/KAMI/files/2521374/KAMI-feature-baritone-impl-10-25-01-future-b9-release.jar.zip)

My Kami settings so you can easily see what I have enabled:
[Kami Settings.zip](https://github.com/zeroeightysix/KAMI/files/2521376/Kami.Settings.zip)

**Comment by EmotionalLove** [comment]
Future isn't open source which means it's hard to tell what's interfering with what in both clients. Unless a certain someone aka 0x22 wants to like help then idk if it'll ever perfectly work with Future

**Comment by ChristoferMinestar** [comment]
@0-x-2-2 care to comment on this? It would really help with solving this issue if you have any knowledge as to why this could be happening.

**Comment by ZeroMemes** [comment]
Really good question: Why do y'all mfs insist on using multiple *utility mods* simultaneously? It's problematic in it's roots.

**Comment by wine** [comment]
@ZeroMemes I agree, instead of using multiple **utility** mods, just request features that you are missing, helps KAMI grow aswell.

**Comment by ChristoferMinestar** [comment]
@wine @zeromemes I use both at the same time to see what I naturally use, and then to see what should be added

**Comment by leijurv** [comment]
educated with logic and facts ---- cant argue with that!!!!

**Comment by zeroeightysix** [comment]
Closed, the baritone branch doesn't exist anymore

**Comment by S-B99** [comment]
Closed due to baritone branch being obselete
