### ISSUE TITLE
Bug: freecam

### ISSUE THREAD

**Issue by dominikaaaa** [zeroeightysix/KAMI#88]
Freecam kicks if you turn on while connected, but once it's on and you reconnect it's fine.

While freecam is on and you are connected it's as if it's holding shift, and freecam falls really fast no matter the speed.

**Comment by zeroeightysix** [comment]
Fixed in 569b4e4f9a531cd740f212f3bbc6709c68a194b5

**Comment by dominikaaaa** [comment]
tfw fixed 2 years later

**Comment by zeroeightysix** [comment]
better than never

**Comment by dominikaaaa** [comment]
"the best time to plant a tree is 20 years ago, the second best time is now"
