### ISSUE TITLE
add an option to enable/disable black background in each mode in the active mods tab 

### ISSUE THREAD

**Issue by 2b2tplayer** [zeroeightysix/KAMI#89]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I don't have a black background in my active mods tab

**Describe the solution you'd like**
Adding it

**Additional context**
https://images-ext-2.discordapp.net/external/tVcbjsPDOgoksD7Oooejl-VXQIG7M1v3-nz61IahP_w/%3Fwidth%3D850%26height%3D480/https/images-ext-2.discordapp.net/external/TbtlsT7HNlQrt2RiVC3BuvDxc_iVyCqJKUxyJwif1ZU/https/cdn.discordapp.com/attachments/397436324849909760/404832214338240515/unknown.png

**Comment by zeroeightysix** [comment]
While not exactly the same, the new fabric GUI does have a toggleable background feature for pinnable widgets. Reopen if you really need this exact style.
