### ISSUE TITLE
ESP modes

### ISSUE THREAD

**Issue by 2b2tplayer** [zeroeightysix/KAMI#92]
**Is your feature request related to a problem? Please describe.**
Just to add a cool ESP outline or somwthing like that

**Describe the solution you'd like**
Just add it, a good one tho, not like future's, I'll include screenshots as examples

EXAMPLES
https://i.imgur.com/LYsO9Rz.png
https://cdn.discordapp.com/attachments/518874650076250143/518891136366936086/unknown.png

**Comment by wine** [comment]
What about a ESP-builder solution where u can change more than just the mode.
Settings like padding, line size, font size, form, colors etc.

**Comment by wine** [comment]
Also maybe a ESP preview on a 3d player model

**Comment by 2b2tplayer** [comment]
yeah it'd be cool, but for now all I'm asking is that esp (the one shown in screenshots) cause I'm stuck using future's which is shit

**Comment by zeroeightysix** [comment]
> Also maybe a ESP preview on a 3d player model in the menu?

definitely something that would be implemented with the new GUI (when I finally get around to finishing that)

Reason we don't have a proper ESP yet is because I'm no openGL wizard and I wouldn't want to add something botched / awful on performace

**Comment by ZeroMemes** [comment]
> awful on performace

This is Minecraft, silly.

**Comment by zeroeightysix** [comment]
Fixed in c575411cbb58d9ab00e916b467a6cdb179c77ffb
