### ISSUE TITLE
Feature: CPU and RAM usage module

### ISSUE THREAD

**Issue by dominikaaaa** [zeroeightysix/KAMI#97]

**Comment by wine** [comment]
How hard is to open task manager on Windows or htop on linux????????? 🤔

**Comment by zeroeightysix** [comment]
Honestly, having this is the info window *could* be useful. I plan on having most windows fully customizeable with the ("soon" to come) new gui, which could introduce this as well.

**Comment by ChristoferMinestar** [comment]
@wine I'm not going to alt tab out of Minecraft when messing with settings, and what if I want to see the usage when rendering terrain behind me? I can change the window size but then it's not rendering at 1080.

**Comment by wine** [comment]
forgot some people play in fullscreen, lol

**Comment by S-B99** [comment]
I implemented a fully customizable info window in my work, I can pull it if you'd like.
Unfortunately I can't find a good way to implement a CPU usage module, everything I tried 'flickers' so it's either showing 0 or 100, look at my commented code [here](https://github.com/S-B99/KAMI/blob/features-master/src/main/java/me/zeroeightsix/kami/gui/kami/KamiGUI.java#L250)

**Comment by zeroeightysix** [comment]
Fixed without CPU variables. Reason mentioned above!
