### ISSUE TITLE
Feature: Custom image for title screen background

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#98]

**Comment by zeroeightysix** [comment]
Along with #99, this is something I (personally) find useless, and in some clients, annoying. If there's actual demand for it, I could implement a configuration option or something for it - but for now, just modify your resource packs to do it for you.

**Comment by ChristoferMinestar** [comment]
How exactly would you change it with a resource pack? I thought that was removed in 1.8

**Comment by ChristoferMinestar** [comment]
Better question, is the plugin system coming after or before 1.13? Because I'd gladly make a plugin for this.
