### ISSUE TITLE
Feature: replace forge/Minecraft logo with Kami logo

### ISSUE THREAD

**Issue by ChristoferMinestar** [zeroeightysix/KAMI#99]
I can make one that's the exact same size as Kami's and look into how other mods do it personally.

**Comment by wine** [comment]
GL11 Display#setIcon

**Comment by ChristoferMinestar** [comment]
That makes it easier, thanks. Now to learn GIMP because I haven't used it in 3 years

**Comment by zeroeightysix** [comment]
See #98
